# Configuration
-include .env

# Defaults (override via .env)
CONTAINER_RUNTIME ?= podman
LAB_PORT ?= 8888
WEBUI_PORT ?= 8443
HOST_WORK_DIR ?= .
HOST_HOME_DIR ?= $(HOME)
HOME_VOLUME ?= $(HOME)/devai-home
APT_PROXY ?=
NO_PROXY ?=

# Derived (not configurable)
COMPOSE = $(CONTAINER_RUNTIME) compose
IMAGE_NAME = devai-lab-cpu
IMAGE_NAME_GPU = devai-lab-gpu
BASE_IMAGE_NAME = devai-base-cpu
BASE_IMAGE_NAME_GPU = devai-base-gpu
CONTAINER_USER = devai
PYTHON_VERSION = 3.13
HOST_IP = $(shell hostname -I | awk '{print $$1}')
OLLAMA_CONTAINER = devai-ollama
OLLAMA_EXEC = $(CONTAINER_RUNTIME) exec $(OLLAMA_CONTAINER) ollama
DEVAI_NETWORK = devai-net
# Internal (no-NAT) network the interactive lab is confined to (egress
# fail-closed). Created with --internal by cache-up; the lab reaches the
# internet only through the pipelock MITM proxy. See docs/pipelock.md.
DEVAI_EGRESS_NETWORK = devai-lab-egress
# Host path for the pipelock MITM CA private key (0600, never committed).
# Generated by `make pipelock-ca-init`; mounted into devai-pipelock by cache-up.
PIPELOCK_CA_KEY ?= $(HOME)/.config/devai/pipelock-ca-key.pem
CACHE_DIR = /var/cache/devai
GPU_MEMORY_GB ?= 24
MAX_CONTEXT_LEN ?= 262144
# Export so recipe shells — and compose interpolation in particular —
# see these values without requiring the user to maintain a .env file.
# Shell-level env wins over compose's `${VAR:-default}` fallback, so the
# devai-router container receives the Makefile values verbatim. Anything
# the user already exported in their shell still wins (?= keeps the
# external value), and `make MAX_CONTEXT_LEN=X cache-up` overrides both.
export GPU_MEMORY_GB MAX_CONTEXT_LEN
# vLLM image: .env (or the shell) overrides; default matches compose's
# fallback. Exported so host-run probers (scripts/probe-vllm-reasoning.py)
# launch the SAME image the router/compose use -- without this a .env
# VLLM_IMAGE bump reaches compose but the prober silently falls back to
# its own hardcoded default, probing the wrong engine. (SGLANG_IMAGE is
# intentionally NOT exported here: it has no .env value, so exporting it
# empty would beat the prober's os.environ.get default and break it.)
VLLM_IMAGE ?= docker.io/vllm/vllm-openai:latest-x86_64-cu129-ubuntu2404
export VLLM_IMAGE
CACHE_COMPOSE = $(CURDIR)/deploy/docker-compose.yaml

# Services `make cache-up` brings up, in compose-declaration order. Listed
# explicitly because cache-up must name them one by one -- see the
# router-managed-container note in that target. Keep in sync with
# deploy/docker-compose.yaml; `make cache-services-check` asserts it.
# mcp-gateway is deliberately absent: it sits behind the `mcp` profile.
CACHE_SERVICES = apt-cache registry-cache ollama vllm sglang router \
                 open-webui webui-proxy logger pipelock

# The three the router recreates on demand. cache-up skips any of these
# that already exist rather than colliding with the router's container.
CACHE_BACKEND_SERVICES = ollama vllm sglang
INFERENCE_CONFIG = deploy/models.yaml
HF_CLI = hf
# vLLM and SGLang safetensors live on their OWN external volumes
# (/dev/mapper/vgais-cache_vllm, -cache_sglang), NOT under the Ollama tree.
# Keeping them out of ollama/ is deliberate: an Ollama cache cleanup must
# never be able to reach non-Ollama weights (see the ollama-clean note).
VLLM_MODELS_DIR = $(CACHE_DIR)/vllm
SGLANG_MODELS_DIR = $(CACHE_DIR)/sglang
# Absolute host path to scripts/vllm_plugins. The router (running in
# its own container) bind-mounts this into the recreated vLLM
# container so models that resolve to a custom tool/reasoning parser
# in deploy/vllm-plugins.json get the plugin .py file at the path
# `--tool-parser-plugin` expects. Exported so compose interpolates it
# into the router's env.
VLLM_PLUGINS_HOST_DIR = $(abspath scripts/vllm_plugins)
export VLLM_PLUGINS_HOST_DIR
OLLAMA_HOST = http://devai-router:11434
# Pinned to a real catalog tag. The previous shell-out read defaults['ollama']
# from models.yaml, which generate-catalog.py never writes — so this always
# fell through to a tag (qwen3.5:9b) that doesn't exist in the catalog.
OLLAMA_DEFAULT_MODEL = qwen3.5:9b-q8_0

# Proxy build args (passed to all container builds)
PROXY_BUILD_ARGS = \
	--build-arg HTTP_PROXY=$(HTTP_PROXY) \
	--build-arg HTTPS_PROXY=$(HTTPS_PROXY) \
	--build-arg NO_PROXY=$(NO_PROXY)

# APT proxy (base image only — apt is not used in the lab layer)
APT_PROXY_ARG = --build-arg APT_PROXY=$(APT_PROXY)
PYTHON_VERSION_ARG = --build-arg PYTHON_VERSION=$(PYTHON_VERSION)

# Hash of cached binaries (invalidates build cache when binaries change)
BIN_HASH = $(shell cat $(CACHE_DIR)/pip/bin/.etags/* 2>/dev/null | md5sum | cut -c1-12)

# Cache mount args (bind host cache dirs into build for pip/uv, npm, and binaries)
CACHE_BUILD_ARGS = \
	--build-arg BIN_HASH=$(BIN_HASH) \
	-v $(CACHE_DIR)/pip:/root/.cache/uv \
	-v $(CACHE_DIR)/npm:/root/.npm \
	-v $(CACHE_DIR)/pip/bin:/var/cache/bin:ro \
	$(if $(wildcard $(CACHE_DIR)/pip/wheels/skypilot),-v $(CACHE_DIR)/pip/wheels/skypilot:/var/cache/wheels/skypilot:ro,)

# Proxy runtime env (passed to all container runs)
PROXY_RUN_ENV = \
	-e HTTP_PROXY=$(HTTP_PROXY) \
	-e HTTPS_PROXY=$(HTTPS_PROXY) \
	-e NO_PROXY=$(NO_PROXY) \
	-e http_proxy=$(HTTP_PROXY) \
	-e https_proxy=$(HTTPS_PROXY) \
	-e no_proxy=$(NO_PROXY)

# Egress-lock env for the interactive lab/shell targets: force ALL egress
# through the pipelock MITM proxy; internal hosts (router, caches) bypass it.
PIPELOCK_PROXY = http://devai-pipelock:8888
PIPELOCK_NO_PROXY = devai-router,router,apt-cache,registry-cache,ollama,devai-mcp-gateway,mcp-gateway,localhost,127.0.0.1,::1
EGRESS_PROXY_ENV = \
	-e HTTP_PROXY=$(PIPELOCK_PROXY) \
	-e HTTPS_PROXY=$(PIPELOCK_PROXY) \
	-e NO_PROXY=$(PIPELOCK_NO_PROXY) \
	-e http_proxy=$(PIPELOCK_PROXY) \
	-e https_proxy=$(PIPELOCK_PROXY) \
	-e no_proxy=$(PIPELOCK_NO_PROXY)


# GPU build settings. Base image defaults on DEVAI_GPU_VENDOR (from .env,
# via -include .env above; set by `make gpu-vendor VENDOR=amd`) -- an
# explicit GPU_BASE_IMAGE in .env or the shell still wins either way
# (?= only assigns when unset). See docs/gpu-vendors.md.
ifeq ($(DEVAI_GPU_VENDOR),amd)
GPU_BASE_IMAGE ?= docker.io/rocm/dev-ubuntu-24.04:6.4.3-complete
else
GPU_BASE_IMAGE ?= docker.io/nvidia/cuda:12.9.1-cudnn-runtime-ubuntu24.04
endif

# Mount host config files (gitconfig, ssh) to staging dir for entrypoint to copy
HOME_MOUNT_ARG =
ifneq ($(HOST_HOME_DIR),)
	HOME_MOUNT_ARG += $(if $(wildcard $(HOME)/.gitconfig),-v "$(HOME)/.gitconfig":/tmp/host-config/.gitconfig:ro)
	HOME_MOUNT_ARG += $(if $(wildcard $(HOME)/.ssh),-v "$(HOME)/.ssh":/tmp/host-config/.ssh:ro)
endif

RUN_FLAGS =

# Read-only mount of the model cache so the in-container picker can do
# disk-based "is downloaded?" detection (ollama manifests + vllm/sglang dirs).
# vLLM/SGLang weights are on their OWN volumes now (see the mount-point
# convention in CLAUDE.md), no longer under ollama/, so each must be mounted
# in separately. The -e VLLM_MODELS_DIR/SGLANG_MODELS_DIR point the picker at
# the new container paths so even a not-yet-rebuilt image (whose baked default
# is the old ollama/models/vllm path) resolves them.
MODEL_CACHE_MOUNT = $(if $(wildcard $(CACHE_DIR)/ollama),-v $(CACHE_DIR)/ollama:/var/cache/devai/ollama:ro) \
	$(if $(wildcard $(VLLM_MODELS_DIR)),-v $(VLLM_MODELS_DIR):/var/cache/devai/vllm:ro) \
	$(if $(wildcard $(SGLANG_MODELS_DIR)),-v $(SGLANG_MODELS_DIR):/var/cache/devai/sglang:ro) \
	-e VLLM_MODELS_DIR=/var/cache/devai/vllm -e SGLANG_MODELS_DIR=/var/cache/devai/sglang

# Read-only mount of the probe caches so the in-container picker can
# render the per-tier menu for every backend and the router can build
# its name → context-cap map. All three caches must be exposed under
# /etc/devai/.<backend>-reasoning-cache.json — model-picker.py looks
# them up by that path. Without the vLLM/SGLang mounts the picker
# falls back to "no HF probes" and shows Ollama rows only. The
# .bench-cache.json mount is what populates the picker's TPS/CODE/
# REAS/TOTAL columns; absent → all four columns render as '-'.
PROBE_CACHE_MOUNT = \
	$(if $(wildcard deploy/.ollama-reasoning-cache.json),-v $(CURDIR)/deploy/.ollama-reasoning-cache.json:/etc/devai/.ollama-reasoning-cache.json:ro) \
	$(if $(wildcard deploy/.vllm-reasoning-cache.json),-v $(CURDIR)/deploy/.vllm-reasoning-cache.json:/etc/devai/.vllm-reasoning-cache.json:ro) \
	$(if $(wildcard deploy/.sglang-reasoning-cache.json),-v $(CURDIR)/deploy/.sglang-reasoning-cache.json:/etc/devai/.sglang-reasoning-cache.json:ro) \
	$(if $(wildcard deploy/.bench-cache.json),-v $(CURDIR)/deploy/.bench-cache.json:/etc/devai/.bench-cache.json:ro)

# User switching: only needed for docker (rootless podman root = host user)
USER_ENV =
ifneq ($(findstring podman,$(CONTAINER_RUNTIME)),podman)
	USER_ENV += -e USER_ID=$(shell id -u) -e GROUP_ID=$(shell id -g)
endif

# Interactive containers run as the devai user (uid 1000), mapped to the host
# user. Rootless podman needs --userns=keep-id so devai's uid 1000 maps back to
# the host uid -- otherwise uid 1000 maps to a subuid and the bind-mounted
# home/work dirs become unwritable. Docker already drops to devai via the
# entrypoint's gosu remap (USER_ENV above), so this is a no-op there.
DEVAI_USER_FLAGS =
ifeq ($(findstring podman,$(CONTAINER_RUNTIME)),podman)
	DEVAI_USER_FLAGS = --userns=keep-id --user devai
endif

# GPU runtime flags
# DEVAI_GPU_DEVICE comes from .env (via -include .env above), written by
# `make gpu-vendor VENDOR=amd` (devai-tools/cmd/devai-gpu-vendor). Defaults
# to NVIDIA's CDI device string when unset -- see docs/gpu-vendors.md.
GPU_FLAGS =
ifeq ($(findstring podman,$(CONTAINER_RUNTIME)),podman)
	GPU_FLAGS += --device $(or $(DEVAI_GPU_DEVICE),nvidia.com/gpu=all) --security-opt=label=disable
else
	GPU_FLAGS += --gpus all
endif

# Compose settings

.PHONY: all build build-cpu build-gpu build-base-cpu build-base-gpu build-router
.PHONY: lab-cpu lab-gpu shell-cpu shell-gpu
.PHONY: cache-up cache-down cache-status cache-clean logs setup-logs
.PHONY: ollama-rm ollama-list ollama-status ollama-clean ollama-df
.PHONY: vllm-list vllm-rm vllm-status vllm-df
.PHONY: clean clean-cpu clean-gpu clean-router prune
.PHONY: fetch-cli pull-images install install-systemd uninstall test test-router test-ollama test-agents test-models test-probe-vllm test-probe-sglang test-probe-ollama-idempotent test-vllm test-sglang test-e2e test-full help
.PHONY: catalog-regen catalog-suggest catalog-discover catalog-discover-add probe probe-vllm probe-sglang probe-load-vllm probe-load-sglang probe-check probe-ornith-arch model-fit model-pull model-status model-sync vram-fit verify-backend-flags ollama-cleanup-ctx-variants
.PHONY: bench bench-vllm bench-sglang bench-ollama bench-report test-bench-smoke
.PHONY: secrets-tmpfs secrets-edit secrets-render secrets-rotate age-keygen-host test-python
.PHONY: build-backup-tool build-gpu-vendor-tool build-mcp-modelstatus build-mcp-modelstatus-image build-devai-tools test-devai-tools
.PHONY: gpu-vendor test-gpu-vendor
.PHONY: backup-create backup-list backup-verify backup-restore test-backup-restore
.PHONY: mcp-up mcp-down mcp-logs mcp-test mcp-health mcp-secrets-render test-mcp-modelstatus

all: help

# =============================================================================
# Fetch external dependencies to local cache (run once)
# =============================================================================


ETAG_DIR = $(CACHE_DIR)/pip/bin/.etags

fetch-cli: ## Download all external binaries and packages to local cache (uses ETags to skip unchanged)
	@mkdir -p $(CACHE_DIR)/pip/bin/gemini $(ETAG_DIR)
	@CC_BUCKET="https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases" \
		&& ARCH=$$(dpkg --print-architecture) \
		&& case "$$ARCH" in amd64) CC_PLATFORM=linux-x64;; arm64) CC_PLATFORM=linux-arm64;; esac \
		&& CC_VERSION=$$(curl -fsSL "$$CC_BUCKET/latest") \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/claude.tmp \
			--etag-compare $(ETAG_DIR)/claude.etag --etag-save $(ETAG_DIR)/claude.etag \
			"$$CC_BUCKET/$$CC_VERSION/$$CC_PLATFORM/claude") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/claude.tmp ]; then \
			rm -f $(CACHE_DIR)/pip/bin/claude.tmp; STATE="up to date"; \
		else \
			mv $(CACHE_DIR)/pip/bin/claude.tmp $(CACHE_DIR)/pip/bin/claude \
			&& chmod +x $(CACHE_DIR)/pip/bin/claude && STATE="updated"; fi \
		&& VERSION=$$($(CACHE_DIR)/pip/bin/claude --version 2>&1 | awk '{print $$1; exit}') \
		&& echo "Claude Code: $$STATE ($$VERSION)"
	@ARCH=$$(dpkg --print-architecture) \
		&& case "$$ARCH" in amd64) CODEX_ARCH=x86_64;; arm64) CODEX_ARCH=aarch64;; esac \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/codex.tar.gz \
			--etag-compare $(ETAG_DIR)/codex.etag --etag-save $(ETAG_DIR)/codex.etag \
			"https://github.com/openai/codex/releases/latest/download/codex-$${CODEX_ARCH}-unknown-linux-musl.tar.gz") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/codex.tar.gz ]; then \
			rm -f $(CACHE_DIR)/pip/bin/codex.tar.gz; STATE="up to date"; \
		else \
			tar -xzf $(CACHE_DIR)/pip/bin/codex.tar.gz -C $(CACHE_DIR)/pip/bin \
			&& mv $(CACHE_DIR)/pip/bin/codex-$${CODEX_ARCH}-unknown-linux-musl $(CACHE_DIR)/pip/bin/codex \
			&& rm -f $(CACHE_DIR)/pip/bin/codex.tar.gz && STATE="updated"; fi \
		&& VERSION=$$($(CACHE_DIR)/pip/bin/codex --version 2>&1 | awk '{print $$2; exit}') \
		&& echo "OpenAI Codex: $$STATE ($$VERSION)"
	@# OpenCode (sst/opencode): single glibc binary, tar.gz with no version in
	@# the asset name -- so latest/download resolves correctly without pinning.
	@ARCH=$$(dpkg --print-architecture) \
		&& case "$$ARCH" in amd64) OC_ARCH=x64;; arm64) OC_ARCH=arm64;; esac \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/opencode.tar.gz \
			--etag-compare $(ETAG_DIR)/opencode.etag --etag-save $(ETAG_DIR)/opencode.etag \
			"https://github.com/sst/opencode/releases/latest/download/opencode-linux-$${OC_ARCH}.tar.gz") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/opencode.tar.gz ]; then \
			rm -f $(CACHE_DIR)/pip/bin/opencode.tar.gz; STATE="up to date"; \
		else \
			tar -xzf $(CACHE_DIR)/pip/bin/opencode.tar.gz -C $(CACHE_DIR)/pip/bin opencode \
			&& chmod +x $(CACHE_DIR)/pip/bin/opencode \
			&& rm -f $(CACHE_DIR)/pip/bin/opencode.tar.gz && STATE="updated"; fi \
		&& VERSION=$$($(CACHE_DIR)/pip/bin/opencode --version 2>&1 | awk '{print $$1; exit}') \
		&& echo "OpenCode: $$STATE ($$VERSION)"
	@ARCH=$$(dpkg --print-architecture) \
		&& case "$$ARCH" in amd64) OL_ARCH=amd64;; arm64) OL_ARCH=arm64;; esac \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/ollama.tar.zst \
			--etag-compare $(ETAG_DIR)/ollama.etag --etag-save $(ETAG_DIR)/ollama.etag \
			"https://github.com/ollama/ollama/releases/latest/download/ollama-linux-$${OL_ARCH}.tar.zst") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/ollama.tar.zst ]; then \
			rm -f $(CACHE_DIR)/pip/bin/ollama.tar.zst; STATE="up to date"; \
		else \
			tar --zstd -xf $(CACHE_DIR)/pip/bin/ollama.tar.zst -C $(CACHE_DIR)/pip/bin --strip-components=1 bin/ollama \
			&& rm -f $(CACHE_DIR)/pip/bin/ollama.tar.zst && STATE="updated"; fi \
		&& VERSION=$$(OLLAMA_HOST= $(CACHE_DIR)/pip/bin/ollama --version 2>&1 | awk '/client version/{print $$NF; exit}') \
		&& echo "Ollama CLI: $$STATE ($$VERSION)"
	@ARCH=$$(dpkg --print-architecture) \
		&& case "$$ARCH" in amd64) CS_ARCH=amd64;; arm64) CS_ARCH=arm64;; esac \
		&& CS_VERSION=$$(curl -fsSL https://api.github.com/repos/coder/code-server/releases/latest | python3 -c "import sys,json; print(json.load(sys.stdin)['tag_name'].lstrip('v'))") \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/code-server.tar.gz \
			--etag-compare $(ETAG_DIR)/code-server.etag --etag-save $(ETAG_DIR)/code-server.etag \
			"https://github.com/coder/code-server/releases/latest/download/code-server-$${CS_VERSION}-linux-$${CS_ARCH}.tar.gz") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/code-server.tar.gz ]; then \
			rm -f $(CACHE_DIR)/pip/bin/code-server.tar.gz; STATE="up to date"; \
		else \
			mkdir -p $(CACHE_DIR)/pip/bin/code-server \
			&& tar -xzf $(CACHE_DIR)/pip/bin/code-server.tar.gz -C $(CACHE_DIR)/pip/bin/code-server --strip-components=1 \
			&& rm -f $(CACHE_DIR)/pip/bin/code-server.tar.gz && STATE="updated"; fi \
		&& VERSION=$$($(CACHE_DIR)/pip/bin/code-server/bin/code-server --version 2>&1 | awk '/^[0-9]+\.[0-9]+\.[0-9]+ /{print $$1; exit}') \
		&& echo "code-server: $$STATE ($$VERSION)"
	@HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/uv.tar.gz \
			--etag-compare $(ETAG_DIR)/uv.etag --etag-save $(ETAG_DIR)/uv.etag \
			"https://github.com/astral-sh/uv/releases/latest/download/uv-x86_64-unknown-linux-gnu.tar.gz") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/uv.tar.gz ]; then \
			rm -f $(CACHE_DIR)/pip/bin/uv.tar.gz; STATE="up to date"; \
		else \
			tar -xzf $(CACHE_DIR)/pip/bin/uv.tar.gz -C $(CACHE_DIR)/pip/bin --strip-components=1 uv-x86_64-unknown-linux-gnu/uv uv-x86_64-unknown-linux-gnu/uvx \
			&& rm -f $(CACHE_DIR)/pip/bin/uv.tar.gz && STATE="updated"; fi \
		&& VERSION=$$($(CACHE_DIR)/pip/bin/uv --version 2>&1 | awk '{print $$2; exit}') \
		&& echo "uv: $$STATE ($$VERSION)"
	@META=$$(curl -fsSL "https://registry.npmjs.org/@google/gemini-cli/latest") \
		&& LATEST=$$(echo "$$META" | python3 -c "import sys,json; print(json.load(sys.stdin)['version'])") \
		&& CACHED=$$(cat $(ETAG_DIR)/gemini.version 2>/dev/null || echo "none") \
		&& if [ "$$LATEST" = "$$CACHED" ]; then echo "Gemini CLI: up to date ($$CACHED)"; else \
			echo "Fetching Gemini CLI $$LATEST..." \
			&& TARBALL=$$(echo "$$META" | python3 -c "import sys,json; print(json.load(sys.stdin)['dist']['tarball'])") \
			&& rm -rf $(CACHE_DIR)/pip/bin/gemini/lib/node_modules/@google/gemini-cli \
			&& mkdir -p $(CACHE_DIR)/pip/bin/gemini/lib/node_modules/@google/gemini-cli \
			&& curl -fsSL "$$TARBALL" | tar -xz -C $(CACHE_DIR)/pip/bin/gemini/lib/node_modules/@google/gemini-cli --strip-components=1 \
			&& mkdir -p $(CACHE_DIR)/pip/bin/gemini/bin \
			&& ln -sf ../lib/node_modules/@google/gemini-cli/bundle/gemini.js $(CACHE_DIR)/pip/bin/gemini/bin/gemini \
			&& echo "$$LATEST" > $(ETAG_DIR)/gemini.version \
			&& echo "Gemini CLI: updated to $$LATEST"; fi
	@ARCH=$$(dpkg --print-architecture) \
		&& case "$$ARCH" in amd64) LATE_ARCH=amd64;; arm64) LATE_ARCH=arm64;; esac \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/late.tmp \
			--etag-compare $(ETAG_DIR)/late.etag --etag-save $(ETAG_DIR)/late.etag \
			"https://github.com/mlhher/late/releases/latest/download/late-linux-$${LATE_ARCH}") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/late.tmp ]; then \
			rm -f $(CACHE_DIR)/pip/bin/late.tmp; STATE="up to date"; \
		else \
			mv $(CACHE_DIR)/pip/bin/late.tmp $(CACHE_DIR)/pip/bin/late \
			&& chmod +x $(CACHE_DIR)/pip/bin/late && STATE="updated"; fi \
		&& VERSION=$$($(CACHE_DIR)/pip/bin/late --version 2>&1 | awk '{print $$2; exit}' | sed 's/^v//') \
		&& echo "LATE: $$STATE ($$VERSION)"
	@# sops + age (sops-age-secrets plan): static Go binaries from GitHub
	@# releases. ETag-stamped per the existing CLI pattern. Both projects
	@# publish single-arch binaries with a -linux-${arch}.tar.gz naming
	@# convention; we curl the asset, verify it's non-empty, and unpack
	@# into /var/cache/devai/pip/bin/.
	@ARCH=$$(dpkg --print-architecture) \
		&& case "$$ARCH" in amd64) SOPS_ARCH=amd64;; arm64) SOPS_ARCH=arm64;; esac \
		&& SOPS_VERSION=$$(curl -fsSL https://api.github.com/repos/getsops/sops/releases/latest | python3 -c "import sys,json; print(json.load(sys.stdin)['tag_name'])") \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/sops.tmp \
			--etag-compare $(ETAG_DIR)/sops.etag --etag-save $(ETAG_DIR)/sops.etag \
			"https://github.com/getsops/sops/releases/latest/download/sops-$${SOPS_VERSION}.linux.$${SOPS_ARCH}") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/sops.tmp ]; then \
			rm -f $(CACHE_DIR)/pip/bin/sops.tmp; STATE="up to date"; \
		else \
			mv $(CACHE_DIR)/pip/bin/sops.tmp $(CACHE_DIR)/pip/bin/sops \
			&& chmod +x $(CACHE_DIR)/pip/bin/sops && STATE="updated"; fi \
		&& VERSION=$$($(CACHE_DIR)/pip/bin/sops --version 2>&1 | awk '{print $$2; exit}' || echo "?") \
		&& echo "sops: $$STATE ($$VERSION)"
	@# SkyPilot wheels (per docs/plans/skypilot-agent-skill.md
	@# decision 1+5). Track upstream PyPI metadata so the lab's `sky`
	@# CLI follows the fast-moving release train without manual
	@# bumps. Same version-stamp pattern the Gemini CLI uses.
	@LATEST=$$(curl -fsSL "https://pypi.org/pypi/skypilot/json" \
	            | python3 -c "import sys,json; print(json.load(sys.stdin)['info']['version'])" 2>/dev/null) \
	    && CACHED=$$(cat $(ETAG_DIR)/skypilot.version 2>/dev/null || echo "none") \
	    && if [ -z "$$LATEST" ]; then echo "SkyPilot: PyPI fetch failed; skipping"; \
	       elif [ "$$LATEST" = "$$CACHED" ]; then echo "SkyPilot: up to date ($$CACHED)"; \
	       else \
	           echo "SkyPilot: fetching $$LATEST wheels..." \
	           && SKY_TMP=$(CACHE_DIR)/pip/wheels/.skypilot.tmp \
	           && rm -rf "$$SKY_TMP" \
	           && mkdir -p "$$SKY_TMP" \
	           && if python3 -m pip download \
	                  'skypilot[aws,gcp,azure,kubernetes,slurm,runpod,lambda]' \
	                  --python-version 3.13 --only-binary=:all: \
	                  --dest "$$SKY_TMP"; then \
	                  rm -rf $(CACHE_DIR)/pip/wheels/skypilot \
	                  && mv "$$SKY_TMP" $(CACHE_DIR)/pip/wheels/skypilot \
	                  && echo "$$LATEST" > $(ETAG_DIR)/skypilot.version \
	                  && echo "SkyPilot: updated to $$LATEST"; \
	              else \
	                  rm -rf "$$SKY_TMP"; \
	                  echo "SkyPilot: download failed (check network / pip); existing cache preserved"; \
	              fi; fi
	@# age + age-keygen ship in one tarball.
	@ARCH=$$(dpkg --print-architecture) \
		&& case "$$ARCH" in amd64) AGE_ARCH=amd64;; arm64) AGE_ARCH=arm64;; esac \
		&& AGE_VERSION=$$(curl -fsSL https://api.github.com/repos/FiloSottile/age/releases/latest | python3 -c "import sys,json; print(json.load(sys.stdin)['tag_name'])") \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/age.tar.gz \
			--etag-compare $(ETAG_DIR)/age.etag --etag-save $(ETAG_DIR)/age.etag \
			"https://github.com/FiloSottile/age/releases/latest/download/age-$${AGE_VERSION}-linux-$${AGE_ARCH}.tar.gz") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/age.tar.gz ]; then \
			rm -f $(CACHE_DIR)/pip/bin/age.tar.gz; STATE="up to date"; \
		else \
			tar -xzf $(CACHE_DIR)/pip/bin/age.tar.gz -C $(CACHE_DIR)/pip/bin --strip-components=1 age/age age/age-keygen \
			&& chmod +x $(CACHE_DIR)/pip/bin/age $(CACHE_DIR)/pip/bin/age-keygen \
			&& rm -f $(CACHE_DIR)/pip/bin/age.tar.gz && STATE="updated"; fi \
		&& VERSION=$$($(CACHE_DIR)/pip/bin/age --version 2>&1 | head -n1 || echo "?") \
		&& echo "age: $$STATE ($$VERSION)"
	@# aiagent (devitops-com/aiagent): a self-extracting makeself bundle (~63 MB)
	@# that carries its own CPython 3.13, so the lab image needs no extra Python
	@# or zstd to run it. ETag-stamped like the other CLIs, which keeps the lab
	@# on the aiagent release train AND -- because BIN_HASH is the md5 of every
	@# etag -- busts the image's binary-install layer whenever the bundle
	@# changes. Dockerfile.lab extracts it to /usr/local (=> /usr/local/bin/
	@# aiagent). Linux x86_64 only; the bootstrap refuses other platforms.
	@AIAGENT_VERSION=$$(curl -fsSL https://api.github.com/repos/devitops-com/aiagent/releases/latest | python3 -c "import sys,json; print(json.load(sys.stdin).get('tag_name','?'))" 2>/dev/null || echo "?") \
		&& HTTP_CODE=$$(curl -fsSL -w '%{http_code}' -o $(CACHE_DIR)/pip/bin/aiagent-install.sh.tmp \
			--etag-compare $(ETAG_DIR)/aiagent.etag --etag-save $(ETAG_DIR)/aiagent.etag \
			"https://github.com/devitops-com/aiagent/releases/latest/download/aiagent-install.sh") \
		&& if [ "$$HTTP_CODE" = "304" ] || [ ! -s $(CACHE_DIR)/pip/bin/aiagent-install.sh.tmp ]; then \
			rm -f $(CACHE_DIR)/pip/bin/aiagent-install.sh.tmp; STATE="up to date"; \
		else \
			mv $(CACHE_DIR)/pip/bin/aiagent-install.sh.tmp $(CACHE_DIR)/pip/bin/aiagent-install.sh \
			&& chmod +x $(CACHE_DIR)/pip/bin/aiagent-install.sh && STATE="updated"; fi \
		&& echo "aiagent: $$STATE ($$AIAGENT_VERSION)"

# Base images used by build and infrastructure
BASE_IMAGES = debian:trixie $(GPU_BASE_IMAGE)
CACHE_IMAGES = $(shell $(COMPOSE) -f $(CACHE_COMPOSE) config --images 2>/dev/null | grep -v devai-)

pull-images: ## Pull latest versions of all base and infrastructure images
	@for img in $(BASE_IMAGES) $(CACHE_IMAGES); do \
		echo "Pulling $$img..." \
		&& $(CONTAINER_RUNTIME) pull "$$img" || true; \
	done

build-base-cpu: ## Build base image with system packages and runtimes (CPU)
	$(CONTAINER_RUNTIME) build --network=host \
		$(PROXY_BUILD_ARGS) \
		$(APT_PROXY_ARG) \
		$(PYTHON_VERSION_ARG) \
		-f deploy/Dockerfile.base \
		-t $(BASE_IMAGE_NAME) .

build-base-gpu: ## Build base image with system packages and runtimes (GPU)
	$(CONTAINER_RUNTIME) build --network=host \
		$(PROXY_BUILD_ARGS) \
		$(APT_PROXY_ARG) \
		$(PYTHON_VERSION_ARG) \
		--build-arg BASE_IMAGE=$(GPU_BASE_IMAGE) \
		-f deploy/Dockerfile.base \
		-t $(BASE_IMAGE_NAME_GPU) .

build: build-cpu build-gpu build-router ## Build all images (CPU + GPU + router)

build-cpu: build-base-cpu fetch-cli ## Build the container image (CPU)
	@[ -f deploy/pipelock-ca.crt ] || { echo "ERROR: deploy/pipelock-ca.crt missing -- run 'make pipelock-ca-init' first (the lab image bakes the pipelock CA into its trust store)."; exit 1; }
	$(CONTAINER_RUNTIME) build --network=host \
		$(PROXY_BUILD_ARGS) \
		$(CACHE_BUILD_ARGS) \
		--build-arg BASE_IMAGE=$(BASE_IMAGE_NAME) \
		--build-arg OLLAMA_HOST=$(OLLAMA_HOST) \
		--build-arg OLLAMA_DEFAULT_MODEL=$(OLLAMA_DEFAULT_MODEL) \
		-f deploy/Dockerfile.lab \
		-t $(IMAGE_NAME) .

build-gpu: build-base-gpu fetch-cli ## Build the container image (GPU/CUDA)
	@[ -f deploy/pipelock-ca.crt ] || { echo "ERROR: deploy/pipelock-ca.crt missing -- run 'make pipelock-ca-init' first (the lab image bakes the pipelock CA into its trust store)."; exit 1; }
	$(CONTAINER_RUNTIME) build --network=host \
		$(PROXY_BUILD_ARGS) \
		$(CACHE_BUILD_ARGS) \
		--build-arg BASE_IMAGE=$(BASE_IMAGE_NAME_GPU) \
		--build-arg GPU_BUILD=true \
		--build-arg GPU_VENDOR=$(or $(DEVAI_GPU_VENDOR),nvidia) \
		--build-arg OLLAMA_HOST=$(OLLAMA_HOST) \
		--build-arg OLLAMA_DEFAULT_MODEL=$(OLLAMA_DEFAULT_MODEL) \
		-f deploy/Dockerfile.lab \
		-t $(IMAGE_NAME_GPU) .


lab-cpu: ## Run the container (CPU)
	@if [ -n "$(HOST_HOME_DIR)" ]; then mkdir -p "$(HOST_HOME_DIR)"; fi
	@echo "Starting $(IMAGE_NAME)..."
	@echo "Access JupyterLab at http://$(HOST_IP):$(LAB_PORT)/lab?token=..."
	$(CONTAINER_RUNTIME) run -it --rm \
		--name $(IMAGE_NAME) \
		$(RUN_FLAGS) \
		$(DEVAI_USER_FLAGS) \
		--network $(DEVAI_EGRESS_NETWORK) \
		$(EGRESS_PROXY_ENV) \
		-e OLLAMA_HOST=$(OLLAMA_HOST) \
		-e OLLAMA_DEFAULT_MODEL=$(OLLAMA_DEFAULT_MODEL) \
		-e CONTEXT=$${CONTEXT:-$(MAX_CONTEXT_LEN)} \
		-e VRAM=$${VRAM:-$(GPU_MEMORY_GB)} \
		$(USER_ENV) \
		-e CONTAINER_USER=$(CONTAINER_USER) \
		-e HOST_IP=$(HOST_IP) \
		-e PORT=$(LAB_PORT) \
		-p 0.0.0.0:$(LAB_PORT):8888 \
		-v $(HOME_VOLUME):/home/$(CONTAINER_USER) \
		$(HOME_MOUNT_ARG) \
		$(MODEL_CACHE_MOUNT) \
		$(PROBE_CACHE_MOUNT) \
		-v "$$(readlink -f $(HOST_WORK_DIR))":/home/$(CONTAINER_USER)/work \
		$(IMAGE_NAME)

lab-gpu: ## Run the container (GPU/CUDA)
	@if [ -n "$(HOST_HOME_DIR)" ]; then mkdir -p "$(HOST_HOME_DIR)"; fi
	@echo "Starting $(IMAGE_NAME_GPU) with GPU support..."
	@echo "Access JupyterLab at http://$(HOST_IP):$(LAB_PORT)/lab?token=..."
	$(CONTAINER_RUNTIME) run -it --rm \
		--name $(IMAGE_NAME_GPU) \
		$(RUN_FLAGS) \
		$(DEVAI_USER_FLAGS) \
		$(GPU_FLAGS) \
		--network $(DEVAI_EGRESS_NETWORK) \
		$(EGRESS_PROXY_ENV) \
		-e OLLAMA_HOST=$(OLLAMA_HOST) \
		-e OLLAMA_DEFAULT_MODEL=$(OLLAMA_DEFAULT_MODEL) \
		-e CONTEXT=$${CONTEXT:-$(MAX_CONTEXT_LEN)} \
		-e VRAM=$${VRAM:-$(GPU_MEMORY_GB)} \
		$(USER_ENV) \
		-e CONTAINER_USER=$(CONTAINER_USER) \
		-e HOST_IP=$(HOST_IP) \
		-e PORT=$(LAB_PORT) \
		-p 0.0.0.0:$(LAB_PORT):8888 \
		-v $(HOME_VOLUME):/home/$(CONTAINER_USER) \
		$(HOME_MOUNT_ARG) \
		$(MODEL_CACHE_MOUNT) \
		$(PROBE_CACHE_MOUNT) \
		-v "$$(readlink -f $(HOST_WORK_DIR))":/home/$(CONTAINER_USER)/work \
		$(IMAGE_NAME_GPU)

shell-cpu: ## Start an interactive shell (CPU)
	$(CONTAINER_RUNTIME) run -it --rm \
		--name $(IMAGE_NAME)-shell \
		$(RUN_FLAGS) \
		$(DEVAI_USER_FLAGS) \
		--network $(DEVAI_EGRESS_NETWORK) \
		$(EGRESS_PROXY_ENV) \
		-e OLLAMA_HOST=$(OLLAMA_HOST) \
		-e OLLAMA_DEFAULT_MODEL=$(OLLAMA_DEFAULT_MODEL) \
		-e CONTEXT=$${CONTEXT:-$(MAX_CONTEXT_LEN)} \
		-e VRAM=$${VRAM:-$(GPU_MEMORY_GB)} \
		$(USER_ENV) \
		-e CONTAINER_USER=$(CONTAINER_USER) \
		-v $(HOME_VOLUME):/home/$(CONTAINER_USER) \
		$(HOME_MOUNT_ARG) \
		$(MODEL_CACHE_MOUNT) \
		$(PROBE_CACHE_MOUNT) \
		-v "$$(readlink -f $(HOST_WORK_DIR))":/home/$(CONTAINER_USER)/work \
		$(IMAGE_NAME) agent-picker

shell-gpu: ## Start an interactive shell (GPU)
	$(CONTAINER_RUNTIME) run -it --rm \
		--name $(IMAGE_NAME_GPU)-shell \
		$(RUN_FLAGS) \
		$(DEVAI_USER_FLAGS) \
		$(GPU_FLAGS) \
		--network $(DEVAI_EGRESS_NETWORK) \
		$(EGRESS_PROXY_ENV) \
		-e OLLAMA_HOST=$(OLLAMA_HOST) \
		-e OLLAMA_DEFAULT_MODEL=$(OLLAMA_DEFAULT_MODEL) \
		-e CONTEXT=$${CONTEXT:-$(MAX_CONTEXT_LEN)} \
		-e VRAM=$${VRAM:-$(GPU_MEMORY_GB)} \
		$(USER_ENV) \
		-e CONTAINER_USER=$(CONTAINER_USER) \
		-v $(HOME_VOLUME):/home/$(CONTAINER_USER) \
		$(HOME_MOUNT_ARG) \
		$(MODEL_CACHE_MOUNT) \
		$(PROBE_CACHE_MOUNT) \
		-v "$$(readlink -f $(HOST_WORK_DIR))":/home/$(CONTAINER_USER)/work \
		$(IMAGE_NAME_GPU) agent-picker

clean: clean-cpu clean-gpu clean-router ## Remove all images (CPU + GPU + router)

clean-cpu: ## Remove the CPU container + base images
	$(CONTAINER_RUNTIME) rmi $(IMAGE_NAME) 2>/dev/null || true
	$(CONTAINER_RUNTIME) rmi $(BASE_IMAGE_NAME) 2>/dev/null || true

clean-gpu: ## Remove the GPU container + base images
	$(CONTAINER_RUNTIME) rmi $(IMAGE_NAME_GPU) 2>/dev/null || true
	$(CONTAINER_RUNTIME) rmi $(BASE_IMAGE_NAME_GPU) 2>/dev/null || true

clean-router: ## Remove the router image
	$(CONTAINER_RUNTIME) rmi devai-router 2>/dev/null || true

prune: ## Clean up dangling images only (keeps tagged images and volumes)
	$(CONTAINER_RUNTIME) image prune -f

# sops/age secret-store scaffold (per docs/plans/sops-age-secrets.md).
# A consumer wraps secrets-render with its own (input, output) pair and
# gates cache-up on the result. mcp-gateway Tier 2 is the only live
# consumer; the cluster-mode and SkyPilot-fleet consumers were frozen on
# 2026-07-25 (see attic/README.md).
SOPS_FILE ?=

secrets-tmpfs: ## Mount /run/devai as a 4 MiB tmpfs (one-time per boot)
	@# Idempotent. Sudo because tmpfs requires CAP_SYS_ADMIN.
	sudo bash deploy/setup-secrets-tmpfs.sh

secrets-edit: ## Edit a sops-encrypted file in place. Pass SOPS_FILE=deploy/<name>.sops.env
	@if [ -z "$(SOPS_FILE)" ]; then \
		echo "ERROR: pass SOPS_FILE=deploy/<name>.sops.env" >&2; exit 2; \
	fi
	sops "$(SOPS_FILE)"

secrets-render: ## Generic single-file render: pass SOPS_FILE and DEST. Consumer plans wrap this with concrete pairs.
	@if [ -z "$(SOPS_FILE)" ] || [ -z "$(DEST)" ]; then \
		echo "ERROR: pass SOPS_FILE=deploy/<name>.sops.env DEST=/run/devai/<name>.env" >&2; \
		echo "       Or use a consumer-plan target (e.g. 'make mcp-secrets-render')." >&2; \
		exit 2; \
	fi
	bash scripts/render-secret.sh "$(SOPS_FILE)" "$(DEST)"

secrets-rotate: ## Re-key every deploy/*.sops.env file against the current .sops.yaml recipient list
	@for f in deploy/*.sops.env; do \
		if [ -f "$$f" ]; then \
			echo ">>> updating keys for $$f"; \
			sops updatekeys -y "$$f"; \
		fi; \
	done

age-keygen-host: ## Generate a per-host age keypair under ~/.config/sops/age/ and print the public key
	bash scripts/age-keygen-host.sh

# devai-tools (devai-tools/go.mod): first-party Go CLIs sibling to
# gpu-arbiter -- devai-backup, devai-mcp-modelstatus, devai-gpu-vendor.
# Built/tested with the host's own Go toolchain (consolidated to the
# current stable release across both modules -- see gpu-arbiter/go.mod),
# not a pinned container: needs Go >= the go.mod floor on PATH.

build-backup-tool: ## Build devai-tools/bin/devai-backup
	cd devai-tools && mkdir -p bin && go build -o bin/devai-backup ./cmd/devai-backup

build-mcp-modelstatus: ## Build devai-tools/bin/devai-mcp-modelstatus
	cd devai-tools && mkdir -p bin && go build -o bin/devai-mcp-modelstatus ./cmd/devai-mcp-modelstatus

build-mcp-modelstatus-image: ## Build the devai-mcp-modelstatus container image (for the MCP gateway catalog)
	$(CONTAINER_RUNTIME) build --network=host \
		-f deploy/Dockerfile.mcp-modelstatus \
		-t devai-mcp-modelstatus .

build-gpu-vendor-tool: ## Build devai-tools/bin/devai-gpu-vendor
	cd devai-tools && mkdir -p bin && go build -o bin/devai-gpu-vendor ./cmd/devai-gpu-vendor

gpu-vendor: build-gpu-vendor-tool ## Switch GPU vendor in .env. VENDOR=nvidia|amd (required)
	@if [ "$(VENDOR)" != "nvidia" ] && [ "$(VENDOR)" != "amd" ]; then \
		echo "ERROR: pass VENDOR=nvidia or VENDOR=amd" >&2; exit 2; \
	fi
	devai-tools/bin/devai-gpu-vendor --env-file .env --vendor $(VENDOR)

test-gpu-vendor: ## Verify the GPU-vendor overlay renders correctly both directions
	bash tests/test-gpu-vendor.sh

build-devai-tools: build-backup-tool build-mcp-modelstatus build-gpu-vendor-tool ## Build every devai-tools/ binary

test-devai-tools: ## Run Go unit tests for devai-tools/ (backup, modelcache, routerclient, gpu-vendor)
	cd devai-tools && go test -race -v -count=1 ./...

# Backup/restore (devai-tools/cmd/devai-backup; see docs/backup-restore.md).
# Snapshots probe/bench caches, ~/.devai/ preferences+sessions, and the
# sops/age key. YES=1 mirrors the confirm-flag convention catalog-discover-add
# already uses for a destructive default-off operation.

backup-create: build-backup-tool ## Snapshot host-local state. DEST=<dir> to override.
	devai-tools/bin/devai-backup snapshot $(if $(DEST),--dest $(DEST))

backup-list: build-backup-tool ## List existing backup archives. DEST=<dir> to override.
	devai-tools/bin/devai-backup list $(if $(DEST),--dest $(DEST))

backup-verify: build-backup-tool ## Verify an archive's integrity. ARCHIVE=<path> (required).
	@if [ -z "$(ARCHIVE)" ]; then echo "ERROR: pass ARCHIVE=path/to/backup.tar.gz" >&2; exit 2; fi
	devai-tools/bin/devai-backup verify --archive "$(ARCHIVE)"

backup-restore: build-backup-tool ## Restore from an archive. ARCHIVE=<path> YES=1 (both required).
	@if [ -z "$(ARCHIVE)" ]; then echo "ERROR: pass ARCHIVE=path/to/backup.tar.gz" >&2; exit 2; fi
	@if [ "$(YES)" != "1" ]; then echo "ERROR: restore overwrites host state -- pass YES=1 to confirm" >&2; exit 2; fi
	devai-tools/bin/devai-backup restore --archive "$(ARCHIVE)" --yes

test-backup-restore: test-devai-tools ## devai-tools Go tests + tests/test-backup-restore.sh
	./tests/test-backup-restore.sh

# MCP gateway (see docs/mcp.md, the source of truth). Third-party
# servers resolve from Docker's official catalog; deploy/mcp-catalog-devai.yaml
# adds only the first-party devai-model-status. Opt-in via the 'mcp'
# compose profile -- cache-up does NOT start it. Two of the 15 enabled
# servers (filesystem, arxiv-mcp-server) currently fail to start pending
# config; the other 13 served 134 tools when last verified.
mcp-up: ## Start the MCP gateway (15 servers; secrets optional)
	$(COMPOSE) -f $(CACHE_COMPOSE) --profile mcp up -d mcp-gateway

mcp-down: ## Stop the MCP gateway
	$(COMPOSE) -f $(CACHE_COMPOSE) stop mcp-gateway || true
	$(COMPOSE) -f $(CACHE_COMPOSE) rm -f mcp-gateway || true

mcp-logs: ## Tail the MCP gateway log
	$(CONTAINER_RUNTIME) logs -f devai-mcp-gateway

mcp-test: ## Smoke-test the running MCP gateway (requires `make mcp-up`)
	bash tests/test-mcp.sh

test-mcp-modelstatus: ## End-to-end test of the devai-model-status MCP server against the live gateway
	bash tests/test-mcp-modelstatus.sh

mcp-health: ## Lightweight /health probe against the running MCP gateway
	bash scripts/mcp-health.sh

mcp-secrets-render: secrets-tmpfs ## Render deploy/mcp-secrets.sops.env to /run/devai/mcp-secrets.env
	@# Phase 2 wrapper around the shared scripts/render-secret.sh.
	@# Operator must have:
	@#   1. ran `make age-keygen-host` once (ships under sops-age plan)
	@#   2. added the printed public key to .sops.yaml
	@#   3. encrypted real values into deploy/mcp-secrets.sops.env via
	@#      `cp .../mcp-secrets.sops.env.example /tmp/mcp.env`,
	@#      `sops --encrypt /tmp/mcp.env > deploy/mcp-secrets.sops.env`,
	@#      `shred -u /tmp/mcp.env`
	@if [ ! -f deploy/mcp-secrets.sops.env ]; then \
		echo "ERROR: deploy/mcp-secrets.sops.env not present." >&2; \
		echo "       See deploy/mcp-secrets.sops.env.example for the" >&2; \
		echo "       expected variable names. Encrypt your file with" >&2; \
		echo "       sops, then re-run this target." >&2; \
		exit 1; \
	fi
	bash scripts/render-secret.sh \
	     deploy/mcp-secrets.sops.env \
	     /run/devai/mcp-secrets.env

# pipelock egress proxy (per docs/pipelock.md). Always-on infra service (no
# profile) brought up by `make cache-up`, which mounts the host CA key.
pipelock-logs: ## Tail the pipelock egress-proxy log
	$(CONTAINER_RUNTIME) logs -f devai-pipelock

pipelock-ca-init: ## One-time: generate the pipelock MITM CA. Cert -> deploy/ (commit); key -> host (0600).
	@mkdir -p "$$(dirname $(PIPELOCK_CA_KEY))"; \
	tmp=$$(mktemp -d); \
	$(CONTAINER_RUNTIME) run --rm -v "$$tmp:/out:z" ghcr.io/luckypipewrench/pipelock:latest \
	    tls init --out /out --org "devai-pipelock" >/dev/null; \
	if [ ! -f "$$tmp/ca.pem" ] || [ ! -f "$$tmp/ca-key.pem" ]; then \
	    echo "ERROR: pipelock tls init did not produce a CA." >&2; rm -rf "$$tmp"; exit 1; \
	fi; \
	cp "$$tmp/ca.pem" deploy/pipelock-ca.crt; \
	install -m 600 "$$tmp/ca-key.pem" "$(PIPELOCK_CA_KEY)"; \
	shred -u "$$tmp/ca-key.pem" 2>/dev/null || true; rm -rf "$$tmp"; \
	echo ""; \
	echo "CA cert -> deploy/pipelock-ca.crt        (local build input; gitignored)"; \
	echo "CA key  -> $(PIPELOCK_CA_KEY)  (0600, host-only, never committed)"; \
	echo "Next: make build-gpu && make cache-up"

test-router: ## Run Go unit tests for gpu-arbiter router
	cd gpu-arbiter && go test -race -v -count=1 ./...

test-python: ## Run Python stdlib unittests (bench/picker schema, pure-Python helpers)
	@# Stdlib-only; runs locally, no container start needed. The bench
	@# harness modules import without third-party deps so unittest can
	@# execute them on any host with Python 3.11+.
	cd $(CURDIR) && python3 -m unittest discover -v -s tests/python -p 'test_*.py'

test-ollama: cache-up ## Run Ollama-only integration tests
	./tests/test-router.sh

# test-vllm and test-idle remain manual-only. The recipes for
# ./tests/test-router-vllm.sh and ./tests/test-router-idle.sh stay in the
# tree but exercise containerRecreate against a live GPU — too slow for
# the default `make test` aggregate. Run them directly when changing
# vLLM/SGLang lifecycle code. See docs/backends.md.

test-probe-vllm: ## Smoke test: probe one HF model via vLLM, assert cache schema
	@# Wall time ~60-120s (one cold vLLM start). Requires `make cache-down`
	@# first — the prober self-checks for running router/vllm/sglang
	@# containers and aborts otherwise.
	./tests/test-probe-vllm.sh

test-probe-sglang: ## Smoke test: probe one HF model via SGLang, assert cache schema
	@# Wall time ~60-120s. Same precondition as test-probe-vllm.
	@# Notes that the schema is correct even when the model can't load
	@# (e.g. SGLang+FP4 on this image — the cache records `fits: false`
	@# with `evidence.kind: "infra"`).
	./tests/test-probe-sglang.sh

test-probe-ollama-idempotent: cache-up ## Verify the refactored Ollama prober is byte-idempotent on a populated cache
	@# Phase 1 byte-identical regression check. Runs `make probe` against
	@# the existing cache (which skips already-cached cells) and diffs
	@# the result. Catches drift in cache I/O, alias reconciliation,
	@# implied-spill builder shape, etc. Wall time ~10-30s.
	./tests/test-probe-ollama-idempotent.sh

test-vllm: cache-up ## Live integration tests for the vLLM backend (chat, ctx switch, GPU exclusion)
	@# Wall time ~3-5 min. Reads deploy/.vllm-reasoning-cache.json to
	@# pick models — skips cleanly when nothing's cached. See
	@# tests/test-router-vllm.sh for the test surface.
	./tests/test-router-vllm.sh

test-sglang: cache-up ## Live integration tests for the SGLang backend (mirror of test-vllm)
	@# Skips entirely when the SGLang cache has no fitting entries
	@# (e.g. when SGLang+FP4 fails on this image — see docs/backends.md).
	./tests/test-router-sglang.sh

test-e2e: cache-up ## End-to-end: picker discovery → agent command → live router chat
	@# Bridges Phase 7 picker tests and Phase 5 router tests. Imports
	@# model-picker.py, runs _discover_models + _build_menu against
	@# live caches, picks an HF row, replays the agent-emitted request
	@# through the router. Skips when no HF row is selectable.
	./tests/test-e2e-picker.sh

test-full: test ## Alias for `make test` (kept for backwards-compat; both run the full suite)
	@true


test-models: cache-up ## Matrix test: every probed model × wire protocol × scenario.
	@# Drives /api/chat, /v1/chat/completions, /v1/messages directly via curl
	@# (faster + more deterministic than spinning up real agent CLIs). For
	@# each candidate model materialises a Modelfile-derived ctx variant
	@# (matching what the picker does) and runs basic / tools / think_auto /
	@# think_off / ctx scenarios. Pin a specific subset via TEST_MODELS=...
	HOST_VRAM=$${VRAM:-$(GPU_MEMORY_GB)} \
	TEST_CTX=$${CONTEXT:-32768} \
	CONTAINER_RUNTIME=$(CONTAINER_RUNTIME) \
	  ./tests/test-model-matrix.sh

test-agents: ## Smoke-test every (agent × backend) cell against the live router
	@# Defensive cleanup: previous probe runs may have left
	@# vllm/sglang containers behind. Harmless when they don't exist.
	@$(CONTAINER_RUNTIME) rm -f devai-vllm devai-sglang 2>/dev/null || true
	@$(MAKE) cache-up
	@mkdir -p $(CURDIR)/tests/.matrix-logs
	@# Run via the default entrypoint so codex config gets seeded into
	@# /home/devai/.codex (CODEX_HOME). Image ENV provides ANTHROPIC_*
	@# and OPENAI_API_KEY so no overrides are needed here.
	$(CONTAINER_RUNTIME) run --rm \
		--name devai-test-agents \
		$(GPU_FLAGS) \
		--network $(DEVAI_NETWORK) \
		-e CONTAINER_USER=devai \
		$(MODEL_CACHE_MOUNT) \
		$(PROBE_CACHE_MOUNT) \
		-v "$(CURDIR)/tests/agent-matrix.sh":/usr/local/bin/agent-matrix:ro \
		-v "$(CURDIR)/tests/.matrix-logs":/var/log/agent-matrix \
		-v $(HOME_VOLUME):/home/devai \
		-e CELL_TIMEOUT=$${CELL_TIMEOUT:-60} \
		-e PROMPT="$${PROMPT:-reply with the single word PONG}" \
		-e ROUTER=devai-router \
		-e LOG_DIR=/var/log/agent-matrix \
		$(IMAGE_NAME_GPU) /usr/local/bin/agent-matrix
	@echo "  logs preserved at $(CURDIR)/tests/.matrix-logs/"

test: test-router test-devai-tools test-python test-backup-restore test-gpu-vendor test-probe-ollama-idempotent test-ollama test-e2e test-vllm test-sglang test-models ## Run every available test in sequence (Go unit + Python unit + Ollama + E2E + vLLM/SGLang integration + matrix + probes; ~30-60 min)
	@# The cache-up suite runs as prerequisites above. Probe smoke tests
	@# require the live backends to be DOWN (the prober self-checks for
	@# router/vllm/sglang containers and aborts otherwise) — they run
	@# last with cache-down/cache-up bracketing so the operator's stack
	@# ends in a known-good state. Failures from probe tests are
	@# captured and re-emitted after `cache-up` so we never leave the
	@# stack down.
	@#
	@# rc=77 is the repo-wide "skipped, precondition absent" convention, the
	@# same one tests/test-mcp.sh and tests/test-gpu-vendor.sh use. Both probe
	@# smoke tests exit 77 when the model they would probe has no weights on
	@# disk -- a host data condition, not a failure. Anything else is real.
	@set -u; \
	echo ""; echo "=== Running cache-down probe tests (final phase) ==="; \
	$(MAKE) cache-down >/dev/null 2>&1 || true; \
	./tests/test-probe-vllm.sh;   vrc=$$?; \
	./tests/test-probe-sglang.sh; src=$$?; \
	$(MAKE) cache-up >/dev/null 2>&1 || true; \
	for rc in "$$vrc" "$$src"; do \
	    if [ "$$rc" -ne 0 ] && [ "$$rc" -ne 77 ]; then \
	        echo "probe-vllm rc=$$vrc, probe-sglang rc=$$src"; exit 1; \
	    fi; \
	done; \
	if [ "$$vrc" -eq 77 ] || [ "$$src" -eq 77 ]; then \
	    echo "probe smoke tests: vllm rc=$$vrc, sglang rc=$$src (77 = skipped, no weights on disk)"; \
	fi

help: ## Show this help message
	@printf "\nDevAI Lab — Containerized AI Development Environment\n\n"
	@printf "  %-44s%s\n" "BUILD" "RUN"
	@printf "  %-44s%s\n" "fetch-cli        Update CLI binaries" "lab-cpu          JupyterLab (CPU)"
	@printf "  %-44s%s\n" "pull-images      Pull base images" "lab-gpu          JupyterLab (GPU)"
	@printf "  %-44s%s\n" "build-cpu        Build image (CPU)" "shell-cpu        Shell (CPU)"
	@printf "  %-44s%s\n" "build-gpu        Build image (GPU)" "shell-gpu        Shell (GPU)"
	@printf "  %s\n" "build-router     Build router image"
	@printf "  %s\n" "build            Build all (CPU+GPU+router)"
	@printf "\n"
	@printf "  %-44s%s\n" "INFRASTRUCTURE" "MAINTENANCE"
	@printf "  %-44s%s\n" "cache-up         Start services" "clean-cpu        Remove image (CPU)"
	@printf "  %-44s%s\n" "cache-down       Stop services" "clean-gpu        Remove image (GPU)"
	@printf "  %-44s%s\n" "cache-status     Show status" "clean-router     Remove router image"
	@printf "  %-44s%s\n" "cache-clean      Remove cached data" "clean            Remove all images"
	@printf "  %-44s%s\n" "" "prune            Prune dangling images"
	@printf "  %-44s%s\n" "" "test             Run integration tests"
	@printf "\n"
	@printf "  %-44s%s\n" "MODELS" "vLLM / SGLang (lifecycle: docs/backends.md)"
	@printf "  %-44s%s\n" "probe            Populate cache for every (VRAM, ctx) tier" "vllm-list        List on-disk vLLM weights"
	@printf "  %-44s%s\n" "model-fit        Print fitting models at VRAM/CONTEXT" "vllm-rm          Remove model"
	@printf "  %-44s%s\n" "model-pull       Download best-fit candidates" "vllm-status      Show status"
	@printf "  %-44s%s\n" "  FAMILY=qwen3.5 scope to one family" ""
	@printf "  %-44s%s\n" "ollama-list      List downloaded models" "vllm-df          Disk usage"
	@printf "  %-44s%s\n" "ollama-rm        Remove model" ""
	@printf "  %-44s%s\n" "ollama-status    Show status" ""
	@printf "  %-44s%s\n" "ollama-df        Disk usage" ""
	@printf "  %s\n" "ollama-clean     Clean partials"
	@printf "\n"
	@printf "  %s\n" "DEPLOY"
	@printf "  %s\n" "install-systemd  Auto-start infrastructure at boot"
	@printf "\n"

# =============================================================================
# Infrastructure services (caches + Ollama + vLLM + Open WebUI)
# =============================================================================

cache-up: ## Start all infrastructure (caches + Ollama + router + Open WebUI; vLLM/SGLang as `sleep` placeholders, recreated on demand)
	@# nvidia_uvm and nvidia_uvm_tools are not pulled in by the display
	@# stack at boot — only by the first CUDA process. The CDI spec
	@# references /dev/nvidia-uvm and /dev/nvidia-uvm-tools, so without
	@# them any GPU container fails with "cannot stat /dev/nvidia-uvm".
	@# nvidia-modprobe is SUID root, idempotent, and a no-op once loaded.
	@if [ -e /dev/nvidia0 ] && [ ! -e /dev/nvidia-uvm ] && command -v nvidia-modprobe >/dev/null 2>&1; then \
		echo "Loading nvidia_uvm kernel module..."; \
		nvidia-modprobe -u -c 0; \
	fi
	@if [ "$(CONTAINER_RUNTIME)" = "podman" ] && ! systemctl --user is-active --quiet podman.socket; then \
		echo "Starting Podman API socket..."; \
		systemctl --user enable --now podman.socket; \
	fi
	@$(CONTAINER_RUNTIME) network exists $(DEVAI_NETWORK) 2>/dev/null || $(CONTAINER_RUNTIME) network create $(DEVAI_NETWORK)
	@$(CONTAINER_RUNTIME) network exists $(DEVAI_EGRESS_NETWORK) 2>/dev/null || $(CONTAINER_RUNTIME) network create --internal $(DEVAI_EGRESS_NETWORK)
	@# Backend services are brought up ONLY when no container of that name
	@# exists. The router replaces each placeholder with its own container
	@# (created through the libpod API, so it carries none of compose's
	@# project labels), and compose therefore does not recognise it as its
	@# own: it tries to create a fresh one and dies on the name collision.
	@#
	@#   Error response from daemon: container create: creating container
	@#   storage: the container name "devai-ollama" is already in use
	@#
	@# That failure took down the WHOLE target, and every test and bench
	@# target depends on cache-up -- so once the router had served a single
	@# Ollama request, `make test-ollama|test-vllm|test-sglang|test-e2e|
	@# test-models` and every `bench-*` could no longer run at all. This is
	@# a large part of why the live suites went so long without being run.
	@#
	@# Skipping is the right behaviour, not a workaround: a router-managed
	@# backend already IS up, and tearing it down here would evict a warm
	@# model on every idempotent `make cache-up`, defeating keep-warm. Use
	@# `make cache-down` when you genuinely want the declared placeholders
	@# back.
	@#
	@# --no-deps is required, not incidental: `router depends_on ollama`,
	@# so without it compose drags the very backend we just skipped back
	@# into the up-set and collides anyway. Safe here because CACHE_SERVICES
	@# names every non-profile service, so nothing needed goes unstarted --
	@# and `make cache-services-check`'s test asserts that list stays in
	@# sync with the compose file.
	@key=$(PIPELOCK_CA_KEY); [ -f "$$key" ] || key=/dev/null; \
	  if [ "$$key" = /dev/null ]; then echo "NOTE: pipelock CA key not found ($(PIPELOCK_CA_KEY)); devai-pipelock stays unhealthy until 'make pipelock-ca-init'."; fi; \
	  svcs=""; \
	  for s in $(CACHE_SERVICES); do \
	    case " $(CACHE_BACKEND_SERVICES) " in \
	      *" $$s "*) \
	        if $(CONTAINER_RUNTIME) container exists devai-$$s 2>/dev/null; then \
	          echo "  note: devai-$$s already running (router-managed); leaving it alone"; \
	        else svcs="$$svcs $$s"; fi ;; \
	      *) svcs="$$svcs $$s" ;; \
	    esac; \
	  done; \
	  PIPELOCK_CA_KEY_FILE=$$key $(COMPOSE) -f $(CACHE_COMPOSE) up -d --no-deps $$svcs
	@echo "Infrastructure services started:"
	@echo "  apt-cacher-ng:     http://localhost:3142"
	@echo "  Registry mirror:   http://localhost:5000"
	@echo "  Router:            devai-router:11434 (unified endpoint)"
	@echo "  Ollama:            devai-ollama:11434 (GGUF models)"
	@echo "  vLLM/SGLang:       devai-router:11435 / 11436 (recreated on first request — see docs/backends.md)"
	@echo "  Open WebUI:        https://localhost:$(WEBUI_PORT)"
	@echo "  Logger:            $(CACHE_DIR)/logs/<container>.log (per-service stdout)"
	@echo ""
	@echo "To pull and probe models:  make model-pull [FAMILY=qwen3.5] && make probe"
	@echo "To tail a service's log:   make logs SERVICE=devai-ollama"

cache-down: ## Stop and remove ALL infrastructure services (running, stopped, orphaned)
	@# -t 0 kills immediately; --remove-orphans catches containers no longer in compose.
	-$(COMPOSE) -f $(CACHE_COMPOSE) down --remove-orphans -t 0
	@# Force-remove the three backend containers explicitly. Compose launches
	@# vllm/sglang as `sleep infinity` placeholders, but the router
	@# (gpu-arbiter) replaces them via libpod when a request arrives — the
	@# recreated container drifts from compose's tracked spec (different
	@# entrypoint, args, no compose labels), so `compose down` may leave it
	@# behind as a zombie that blocks the next `cache-up` with "container
	@# name already in use". Remove by name, ignoring missing-container errors.
	@#
	@# devai-ollama belongs in this list too: since the per-model KV-cache
	@# dtype work the router ALSO recreates it (ensureOllamaRunning ->
	@# containerRecreate, to bake in OLLAMA_KV_CACHE_TYPE /
	@# OLLAMA_FLASH_ATTENTION for a mixed-KV tier), which strips the compose
	@# labels exactly the same way. Verified on the reference host: after any
	@# run that serves an Ollama model, `podman inspect devai-ollama` shows an
	@# empty com.docker.compose.project while devai-router still shows
	@# [deploy], and the next `cache-up` dies on the name collision.
	@for name in devai-vllm devai-sglang devai-ollama; do \
		$(CONTAINER_RUNTIME) rm -f $$name >/dev/null 2>&1 || true; \
	done

setup-logs: ## One-time: create dedicated 100G LV at /var/cache/devai/logs (requires sudo).
	@# Stops cache so nothing holds the old logs path open, then runs the
	@# setup script under sudo (LVM + mkfs.xfs + /etc/fstab + mount). The
	@# script is idempotent — re-running on an already-set-up host does
	@# nothing destructive. Override SIZE/VG/LV via env if desired.
	@$(MAKE) cache-down
	@echo
	sudo SIZE=$${SIZE:-100G} VG=$${VG:-vgais} LV=$${LV:-cache_logs} \
	     POOL=$${POOL:-cachepool} RECREATE=$${RECREATE:-0} \
	  deploy/setup-logs-volume.sh
	@echo
	@echo "Next: run 'make cache-up' to start services on the new logs volume."

logs: ## Tail container stdout via the logger sidecar (SERVICE=devai-X, default devai-ollama; LINES=N to seed).
	@svc="$${SERVICE:-devai-ollama}"; \
	 lines="$${LINES:-50}"; \
	 file="$(CACHE_DIR)/logs/$$svc.log"; \
	 if [ ! -f "$$file" ]; then \
	    echo "no log for $$svc at $$file"; \
	    echo "available services:"; \
	    ls -1 $(CACHE_DIR)/logs 2>/dev/null | sed 's/^/  /; s/\.log$$//'; \
	    exit 1; \
	 fi; \
	 echo "tailing $$file (Ctrl-C to stop)"; \
	 tail -n $$lines -f "$$file"

cache-status: ## Show infrastructure service status and disk usage
	@$(COMPOSE) -f $(CACHE_COMPOSE) ps
	@echo ""
	@echo "Cache disk usage:"
	@du -sh $(CACHE_DIR)/*/ 2>/dev/null; true; true
	@echo ""
	@echo "Ollama models:"
	@out=$$($(OLLAMA_EXEC) list 2>/dev/null); \
	if [ -n "$$out" ]; then \
		header=$$(printf '%s' "$$out" | head -n1); \
		body=$$(printf '%s' "$$out" | tail -n +2 | sort -V -f); \
		printf '%s\n%s\n' "$$header" "$$body"; \
	else \
		echo "  (ollama not running)"; \
	fi
	@echo ""
	@echo "vLLM/SGLang models:"
	@vllm_cache=$(CURDIR)/deploy/.vllm-reasoning-cache.json; \
	sglang_cache=$(CURDIR)/deploy/.sglang-reasoning-cache.json; \
	found=false; for dir in $$(ls -d $(VLLM_MODELS_DIR)/*/ 2>/dev/null | sort -V -f); do \
		[ -f "$$dir/config.json" ] || continue; \
		if ! $$found; then \
			printf "%-46s%-16s%-14s%-10s%-20s\n" "NAME" "ID" "BACKENDS" "SIZE" "MODIFIED"; \
			found=true; \
		fi; \
		name=$$(basename "$$dir"); \
		size=$$(du -sh "$$dir" | cut -f1); \
		id=$$(sha256sum "$$dir/config.json" | cut -c1-12); \
		mod_epoch=$$(stat -c '%Y' "$$dir/config.json"); \
		now_epoch=$$(date +%s); \
		diff_sec=$$((now_epoch - mod_epoch)); \
		if [ $$diff_sec -lt 60 ]; then modified="$$diff_sec seconds ago"; \
		elif [ $$diff_sec -lt 3600 ]; then modified="$$((diff_sec / 60)) minutes ago"; \
		elif [ $$diff_sec -lt 86400 ]; then modified="$$((diff_sec / 3600)) hours ago"; \
		elif [ $$diff_sec -lt 604800 ]; then modified="$$((diff_sec / 86400)) days ago"; \
		else modified="$$((diff_sec / 604800)) weeks ago"; fi; \
		backends=""; \
		[ -f "$$vllm_cache" ]   && grep -q "\"$$name\"" "$$vllm_cache"   && backends="vllm"; \
		[ -f "$$sglang_cache" ] && grep -q "\"$$name\"" "$$sglang_cache" && backends="$${backends:+$$backends,}sglang"; \
		[ -z "$$backends" ] && backends="-"; \
		printf "%-46s%-16s%-14s%-10s%-20s\n" "$$name" "$$id" "$$backends" "$$size" "$$modified"; \
	done; \
	$$found || echo "  (none — run 'make model-pull' to populate)"

cache-clean: ## Remove all cached data (keeps volumes mounted, preserves podman graphroot)
	$(COMPOSE) -f $(CACHE_COMPOSE) down
	@echo "Cleaning cache directories..."
	@# $(CACHE_DIR)/registry co-hosts podman's graphroot AND the registry:2 pull-through cache
	@# (see README "Storage Layout"). Wiping registry/* would destroy podman image storage,
	@# so we target only the registry:2 subtree (registry/docker) and guard every path
	@# against overlap with the container runtime's graphroot.
	@# Container-managed caches (apt-cacher-ng, registry:2) contain files owned by
	@# subuids, so the cleanup runs under `podman unshare` to access them.
	@graphroot=$$($(CONTAINER_RUNTIME) info --format '{{.Store.GraphRoot}}' 2>/dev/null \
	              || $(CONTAINER_RUNTIME) info --format '{{.DockerRootDir}}' 2>/dev/null \
	              || true); \
	targets="$(CACHE_DIR)/registry/docker $(CACHE_DIR)/apt $(CACHE_DIR)/pip $(CACHE_DIR)/npm"; \
	for target in $$targets; do \
		if [ -n "$$graphroot" ]; then \
			case "$$graphroot/" in \
				"$$target"/*) \
					echo "ERROR: refusing to clean $$target — $(CONTAINER_RUNTIME) graphroot ($$graphroot) is inside it."; \
					echo "       Relocate graphroot or clean selectively by hand."; \
					exit 1;; \
			esac; \
		fi; \
	done; \
	if [ "$(CONTAINER_RUNTIME)" = "podman" ]; then \
		wrap="$(CONTAINER_RUNTIME) unshare"; \
	else \
		wrap=""; \
	fi; \
	for target in $$targets; do \
		[ -d "$$target" ] || continue; \
		$$wrap find "$$target" -mindepth 1 -maxdepth 1 -exec rm -rf {} +; \
		echo "  cleaned $$target/"; \
	done
	@echo "Cache cleaned. Podman graphroot preserved."

ollama-rm: ## Remove an Ollama model and clean up (usage: make ollama-rm MODEL=llama3.2)
	$(OLLAMA_EXEC) rm $(MODEL)
	@$(MAKE) --no-print-directory ollama-clean

ollama-list: ## List downloaded models with catalog info (sizes, purpose)
	@INFERENCE_CONFIG=$(INFERENCE_CONFIG) CONTAINER_RUNTIME=$(CONTAINER_RUNTIME) OLLAMA_CONTAINER=$(OLLAMA_CONTAINER) \
		python3 scripts/ollama-list.py


ollama-status: ## Show Ollama container status
	@$(CONTAINER_RUNTIME) inspect -f '{{.State.Status}}' $(OLLAMA_CONTAINER) 2>/dev/null || echo "not running"
	@$(OLLAMA_EXEC) ps 2>/dev/null || true

ollama-clean: ## Remove partial downloads and orphaned blobs from Ollama cache
	@echo "Removing partial downloads..."
	@rm -vf $(CACHE_DIR)/ollama/models/blobs/*-partial* 2>/dev/null || true
	@echo "Removing orphaned blobs..."
	@for b in $(CACHE_DIR)/ollama/models/blobs/sha256-*; do \
		[ -f "$$b" ] || continue; \
		case "$$b" in *-partial*) continue;; esac; \
		bname=$$(basename "$$b" | sed 's/-/:/'); \
		if ! grep -rq "$$bname" $(CACHE_DIR)/ollama/models/manifests/ 2>/dev/null; then \
			rm -v "$$b"; \
		fi; \
	done
	@# GGUF staging dirs only. Do NOT add vllm/sglang here: those weights
	@# now live on their own volumes ($(VLLM_MODELS_DIR), $(SGLANG_MODELS_DIR)),
	@# outside the ollama tree. This loop keys "orphaned" off the Ollama
	@# manifests, so including a non-Ollama dir would delete every HF model
	@# whose name isn't an Ollama tag -- the exact bug that once wiped the
	@# entire vLLM store. Keep this scoped to ollama's own gguf/ staging.
	@echo "Removing orphaned gguf caches..."
	@for dir in $(CACHE_DIR)/ollama/models/gguf/*; do \
		[ -d "$$dir" ] || continue; \
		model=$$(basename "$$dir"); \
		if ! find $(CACHE_DIR)/ollama/models/manifests/ -path "*$$model*" -print -quit 2>/dev/null | grep -q .; then \
			rm -rvf "$$dir"; \
		fi; \
	done
	@echo "Done. Restart Ollama to reclaim space: $(CONTAINER_RUNTIME) restart $(OLLAMA_CONTAINER)"

ollama-df: ## Show Ollama cache disk usage breakdown
	@echo "=== Ollama disk usage ==="
	@df -h $(CACHE_DIR)/ollama
	@echo ""
	@echo "=== Breakdown ==="
	@du -sh $(CACHE_DIR)/ollama/models/blobs/ 2>/dev/null || true
	@du -sh $(CACHE_DIR)/ollama/models/gguf/ 2>/dev/null || true
	@du -sh $(VLLM_MODELS_DIR)/ 2>/dev/null || true
	@du -sh $(SGLANG_MODELS_DIR)/ 2>/dev/null || true
	@echo ""
	@partials=$$(ls $(CACHE_DIR)/ollama/models/blobs/*-partial 2>/dev/null | wc -l); \
	if [ "$$partials" -gt 0 ]; then \
		echo "WARNING: $$partials partial download(s) found. Run 'make ollama-clean' to remove."; \
		for p in $(CACHE_DIR)/ollama/models/blobs/*-partial; do \
			[ -f "$$p" ] || continue; \
			size=$$(du -sh "$$p" | cut -f1); \
			hash=$$(basename "$$p" | sed 's/-partial.*//; s/-/:/'); \
			model=$$(grep -rl "$$hash" $(CACHE_DIR)/ollama/models/manifests/ 2>/dev/null \
				| head -1 | sed 's|.*/library/||; s|/|:|'); \
			age=$$(( $$(date +%s) - $$(stat -c %Y "$$p") )); \
			if [ "$$age" -lt 60 ]; then status="downloading"; else status="stale"; fi; \
			echo "  $$size	$${model:-unknown}	($$status)"; \
		done; \
	else \
		echo "No partial downloads."; \
	fi

# =============================================================================
# vLLM targets (NVFP4 on Blackwell)
# =============================================================================

vllm-list: ## List vLLM models with status
	@INFERENCE_CONFIG=$(INFERENCE_CONFIG) VLLM_MODELS_DIR=$(VLLM_MODELS_DIR) \
		python3 scripts/vllm-list.py

hf-link: ## Hard-link HF weights between the vLLM and SGLang stores (FROM=vllm TO=sglang [NAME=<model>] [DRY_RUN=1])
	@VLLM_MODELS_DIR=$(VLLM_MODELS_DIR) SGLANG_MODELS_DIR=$(SGLANG_MODELS_DIR) \
		python3 scripts/link-hf-store.py \
			--from $${FROM:-vllm} --to $${TO:-sglang} \
			$(if $(NAME),--name $(NAME),) \
			$(if $(DRY_RUN),--dry-run,)

vram-fit: ## Show which models from the full catalog fit in VRAM (planning aid; use model-pull to act)
	@GPU_MEMORY_GB=$${VRAM:-$(GPU_MEMORY_GB)} MAX_CONTEXT_LEN=$${CONTEXT:-$(MAX_CONTEXT_LEN)} \
		python3 scripts/vram-fit.py \
			$(if $(VRAM),--vram $(VRAM),) \
			$(if $(CONTEXT),--context $(CONTEXT),) \
			$(if $(KV),--kv-dtype $(KV),) \
			$(if $(FAMILY),--family $(FAMILY),) \
			$(if $(FITS_ONLY),--fits-only,) \
			--models-yaml $(INFERENCE_CONFIG) \
			--vllm-dir $(VLLM_MODELS_DIR)

PROBE_VRAMS    ?= 16G,24G
PROBE_CONTEXTS ?= 32K,64K,128K,256K
# KV-cache dtype for THIS probe pass (empty = daemon default f16). Cells
# probed with PROBE_KV_CACHE_TYPE=q8_0 are stamped kv_cache_type=q8_0 in
# the cache; the router then reproduces that dtype when serving a ctx the
# cell covers. Typical use: force just the tier that only fits quantized,
# e.g. PROBE_FORCE_CTX=128K PROBE_KV_CACHE_TYPE=q8_0 PROBE_FLASH_ATTENTION=1.
PROBE_KV_CACHE_TYPE   ?=
PROBE_FLASH_ATTENTION ?=
# Seconds to wait for the recreated devai-ollama to answer `ollama list`
# before `make probe` gives up. Bounded so a daemon that never comes up
# fails loudly instead of hanging the probe run forever.
PROBE_READY_TIMEOUT   ?= 180

probe: ## Probe every downloaded ollama digest at every (VRAM, CONTEXT) tier.
	@# Loops over PROBE_VRAMS, recreating devai-ollama with
	@# OLLAMA_GPU_OVERHEAD set so the daemon behaves as a smaller card.
	@# A 24G host can therefore produce cache entries valid for 16G targets.
	@# Each probe pass is incremental: existing (vram, ctx) cells are
	@# never overwritten unless PROBE_FORCE=1 or PROBE_FORCE_CTX=<list>.
	@# The restore below runs from an EXIT trap so an aborted or failed
	@# probe never leaves devai-ollama with the VRAM-crippling
	@# OLLAMA_GPU_OVERHEAD still set (a later `make bench-ollama` against
	@# such a container would record wrong numbers).
	@set -e; \
	 restore_ollama() { \
	    rc=$$?; \
	    echo; \
	    echo ">>> restoring devai-ollama to host VRAM (no overhead)"; \
	    $(CONTAINER_RUNTIME) rm -f $(OLLAMA_CONTAINER) >/dev/null 2>&1 || true; \
	    OLLAMA_GPU_OVERHEAD=0 $(COMPOSE) -f $(CACHE_COMPOSE) up -d ollama || rc=$$?; \
	    exit $$rc; \
	 }; \
	 trap restore_ollama EXIT; \
	 trap 'exit 130' INT TERM; \
	 for vram in $$(echo $(PROBE_VRAMS) | tr ',' ' '); do \
	    overhead_bytes=$$(python3 -c "import sys; sys.path.insert(0, 'scripts'); from _contexts import parse_vram_token, vram_overhead_bytes; print(vram_overhead_bytes($(GPU_MEMORY_GB), parse_vram_token('$$vram')))"); \
	    echo; \
	    echo ">>> probing at VRAM=$$vram (host=$(GPU_MEMORY_GB)G, OLLAMA_GPU_OVERHEAD=$$overhead_bytes bytes)"; \
	    $(CONTAINER_RUNTIME) rm -f $(OLLAMA_CONTAINER) >/dev/null 2>&1 || true; \
	    OLLAMA_GPU_OVERHEAD=$$overhead_bytes \
	    OLLAMA_KV_CACHE_TYPE="$(PROBE_KV_CACHE_TYPE)" \
	    OLLAMA_FLASH_ATTENTION="$(PROBE_FLASH_ATTENTION)" \
	      $(COMPOSE) -f $(CACHE_COMPOSE) up -d ollama; \
	    waited=0; \
	    until $(CONTAINER_RUNTIME) exec $(OLLAMA_CONTAINER) ollama list >/dev/null 2>&1; do \
	        waited=$$((waited + 1)); \
	        if [ $$waited -ge $(PROBE_READY_TIMEOUT) ]; then \
	            echo "ERROR: $(OLLAMA_CONTAINER) did not answer 'ollama list' within $(PROBE_READY_TIMEOUT)s." >&2; \
	            echo "       Inspect its log with: make logs SERVICE=$(OLLAMA_CONTAINER)" >&2; \
	            exit 1; \
	        fi; \
	        sleep 1; \
	    done; \
	    $(CONTAINER_RUNTIME) run --rm \
	        --network $(DEVAI_NETWORK) \
	        -v $(CURDIR)/scripts:/scripts:ro \
	        -v $(CURDIR)/deploy:/deploy \
	        -e OLLAMA_HOST=http://devai-ollama:11434 \
	        -e PROBE_CONTEXTS=$(PROBE_CONTEXTS) \
	        -e OLLAMA_KV_CACHE_TYPE="$(PROBE_KV_CACHE_TYPE)" \
	        --entrypoint python3 \
	        $(IMAGE_NAME) \
	        /scripts/probe-ollama-reasoning.py \
	            --cache /deploy/.ollama-reasoning-cache.json \
	            --vram $$vram \
	            $(if $(PROBE_FORCE),--force,) \
	            $(if $(PROBE_FORCE_CTX),--force-ctx $(PROBE_FORCE_CTX),) \
	            $(PROBE_MODELS); \
	 done

probe-vllm: ## Probe every downloaded vLLM/HF model per (VRAM, CONTEXT) cell.
	@# Pre-condition: devai-router, devai-vllm, and devai-sglang must
	@# be stopped — the prober launches devai-vllm-probe with explicit
	@# GPU exclusivity. The script self-checks and aborts otherwise.
	@# Knobs:
	@#   PROBE_VRAMS_VLLM=16G,24G    target VRAM bands
	@#   PROBE_CONTEXTS=32K,...      ctx tiers
	@#   PROBE_REPO=<regex>          filter catalog rows by repo
	@#   PROBE_FORCE=1               re-probe every cell
	@#   PROBE_FORCE_ARCH=1          re-probe top-level capability/arch
	@#   PROBE_KV_CACHE_TYPE=auto    KV dtype for this pass (default fp8);
	@#                               cells are stamped so serve time
	@#                               reproduces the measured dtype
	PROBE_KV_CACHE_TYPE="$(PROBE_KV_CACHE_TYPE)" \
	python3 scripts/probe-vllm-reasoning.py \
	    --host-vram-gb $(GPU_MEMORY_GB) \
	    --models-dir $(VLLM_MODELS_DIR) \
	    $(if $(PROBE_VRAMS_VLLM),--vram $(PROBE_VRAMS_VLLM),) \
	    $(if $(PROBE_CONTEXTS),--ctx $(PROBE_CONTEXTS),) \
	    $(if $(PROBE_REPO),--repo '$(PROBE_REPO)',) \
	    $(if $(PROBE_FORCE),--force,) \
	    $(if $(PROBE_FORCE_ARCH),--force-arch,)

probe-sglang: ## Probe every downloaded SGLang/HF model per (VRAM, CONTEXT) cell.
	@# Pre-condition: same as probe-vllm — all GPU-owning backends down.
	@# Knobs:
	@#   PROBE_VRAMS_SGLANG=16G,24G  target VRAM bands
	@#   PROBE_CONTEXTS=32K,...      ctx tiers
	@#   PROBE_REPO=<regex>          filter catalog rows by repo
	@#   PROBE_FORCE=1               re-probe every cell
	@#   PROBE_FORCE_ARCH=1          re-probe top-level capability/arch
	@#   PROBE_KV_CACHE_TYPE=fp8_e5m2  enforce a KV dtype for this pass
	@#                               (default: none = engine default);
	@#                               cells are stamped so serve time
	@#                               reproduces the measured dtype
	PROBE_KV_CACHE_TYPE="$(PROBE_KV_CACHE_TYPE)" \
	python3 scripts/probe-sglang-reasoning.py \
	    --host-vram-gb $(GPU_MEMORY_GB) \
	    --models-dir $(SGLANG_MODELS_DIR) \
	    $(if $(PROBE_VRAMS_SGLANG),--vram $(PROBE_VRAMS_SGLANG),) \
	    $(if $(PROBE_CONTEXTS),--ctx $(PROBE_CONTEXTS),) \
	    $(if $(PROBE_REPO),--repo '$(PROBE_REPO)',) \
	    $(if $(PROBE_FORCE),--force,) \
	    $(if $(PROBE_FORCE_ARCH),--force-arch,)

probe-load-vllm: ## Serving-time LOAD probe for vLLM: augment fit cache with serving_ok/transient/needle, ascending ctx, stop at OOM.
	@# Layers onto deploy/.vllm-reasoning-cache.json — run `make probe-vllm`
	@# first so the fit cells exist. Same GPU-exclusivity precondition as
	@# probe-vllm (devai-router/vllm/sglang stopped; the script self-checks).
	@# Knobs:
	@#   PROBE_CONTEXTS=32K,...      ctx tiers (ascending; stops at first OOM)
	@#   PROBE_REPO=<regex>          filter catalog rows by repo
	@#   PROBE_FORCE=1               re-run cells that already have serving_ok
	@#   PROBE_NEEDLE_DEPTH=0.5      needle insertion depth (0.0 top, 1.0 bottom)
	@#   PROBE_KV_CACHE_TYPE=auto    KV dtype for the relaunches -- MUST match
	@#                               the dtype the target cells were fit-probed
	@#                               with (default fp8), or serving numbers are
	@#                               measured under the wrong dtype
	PROBE_KV_CACHE_TYPE="$(PROBE_KV_CACHE_TYPE)" \
	python3 scripts/probe-vllm-reasoning.py --load \
	    --host-vram-gb $(GPU_MEMORY_GB) \
	    --models-dir $(VLLM_MODELS_DIR) \
	    $(if $(PROBE_CONTEXTS),--ctx $(PROBE_CONTEXTS),) \
	    $(if $(PROBE_REPO),--repo '$(PROBE_REPO)',) \
	    $(if $(PROBE_FORCE),--force,) \
	    $(if $(PROBE_NEEDLE_DEPTH),--needle-depth $(PROBE_NEEDLE_DEPTH),)

probe-load-sglang: ## Serving-time LOAD probe for SGLang: same as probe-load-vllm against the SGLang cache.
	@# Layers onto deploy/.sglang-reasoning-cache.json — run `make probe-sglang`
	@# first. Same precondition + knobs as probe-load-vllm.
	PROBE_KV_CACHE_TYPE="$(PROBE_KV_CACHE_TYPE)" \
	python3 scripts/probe-sglang-reasoning.py --load \
	    --host-vram-gb $(GPU_MEMORY_GB) \
	    --models-dir $(SGLANG_MODELS_DIR) \
	    $(if $(PROBE_CONTEXTS),--ctx $(PROBE_CONTEXTS),) \
	    $(if $(PROBE_REPO),--repo '$(PROBE_REPO)',) \
	    $(if $(PROBE_FORCE),--force,) \
	    $(if $(PROBE_NEEDLE_DEPTH),--needle-depth $(PROBE_NEEDLE_DEPTH),)

model-fit: ## Print which models fit at the chosen (VRAM, CONTEXT) — diagnostic, no writes.
	@OLLAMA_CONTAINER=$(OLLAMA_CONTAINER) CONTAINER_RUNTIME=$(CONTAINER_RUNTIME) \
	 VLLM_MODELS_DIR=$(VLLM_MODELS_DIR) SGLANG_MODELS_DIR=$(SGLANG_MODELS_DIR) \
	 HF_CLI=$(HF_CLI) \
	 GPU_MEMORY_GB=$${VRAM:-$(GPU_MEMORY_GB)} MAX_CONTEXT_LEN=$${CONTEXT:-$(MAX_CONTEXT_LEN)} \
	 VERBOSE=$${VERBOSE:-0} \
		python3 scripts/select-models.py \
			$(if $(FAMILY),--family $(FAMILY),) \
			$(if $(VRAM),--vram $(VRAM),) \
			$(if $(CONTEXT),--context $(CONTEXT),) \
			$(if $(CONTEXTS),--contexts $(CONTEXTS),) \
			$(if $(KV),--kv-dtype $(KV),)

model-pull: ## Pull missing best-fit candidates from the catalog (catalog-driven downloads).
	@set -e; \
	 OLLAMA_CONTAINER=$(OLLAMA_CONTAINER) CONTAINER_RUNTIME=$(CONTAINER_RUNTIME) \
	 VLLM_MODELS_DIR=$(VLLM_MODELS_DIR) SGLANG_MODELS_DIR=$(SGLANG_MODELS_DIR) \
	 HF_CLI=$(HF_CLI) \
	 GPU_MEMORY_GB=$${VRAM:-$(GPU_MEMORY_GB)} MAX_CONTEXT_LEN=$${CONTEXT:-$(MAX_CONTEXT_LEN)} \
	 VERBOSE=$${VERBOSE:-0} \
		python3 scripts/select-models.py \
			$(if $(FAMILY),--family $(FAMILY),) \
			$(if $(NAME),--name $(NAME),) \
			$(if $(VRAM),--vram $(VRAM),) \
			$(if $(CONTEXT),--context $(CONTEXT),) \
			$(if $(CONTEXTS),--contexts $(CONTEXTS),) \
			$(if $(KV),--kv-dtype $(KV),) \
			--download \
			$(if $(DOWNLOAD_LIMIT),--max-downloads $(DOWNLOAD_LIMIT),) \
			$(if $(PRUNE),--prune,) \
			$(if $(PRUNE_SHADOWS),--prune-shadows,) \
			$(if $(DRY_RUN),--dry-run,); \
	 echo; \
	 echo "  next: 'make probe' to populate cache cells for any newly pulled tags"

catalog-regen: ## Regenerate deploy/models.yaml from scripts/model-families.yaml using live upstream data
	python3 scripts/generate-catalog.py

catalog-suggest: ## Suggest GGUF candidates llmfit ranks well that aren't yet in scripts/model-families.yaml. Read-only; probe before adding.
	@command -v llmfit >/dev/null 2>&1 || { \
	  echo "error: llmfit not found in PATH (install: https://github.com/AlexsJones/llmfit)"; exit 1; }
	@VRAM=$${VRAM:-$(GPU_MEMORY_GB)}; \
	 CTX=$${CONTEXT:-$(MAX_CONTEXT_LEN)}; \
	 LIMIT=$${LIMIT:-30}; \
	 echo "# llmfit recommend --runtime llamacpp --memory $${VRAM}G --max-context $${CTX} -n $${LIMIT}"; \
	 echo; \
	 llmfit --memory "$${VRAM}G" --max-context "$${CTX}" \
	   recommend --runtime llamacpp --json -n "$${LIMIT}" \
	   $(if $(USE_CASE),--use-case $(USE_CASE),) \
	   $(if $(MIN_FIT),--min-fit $(MIN_FIT),) \
	 | python3 scripts/llmfit-catalog-diff.py

catalog-discover: ## Find newer-version members of tracked lineages (e.g. qwen3.7 when qwen3.5 is tracked) within the GPU's usable VRAM band. Read-only; probe before adding.
	@#   FAMILY=<substr>      scope to lineages whose family name contains this
	@#   INCLUDE_SAME=1       list every untracked repo at a tracked version
	@#   INCLUDE_OVERSIZED=1  also show candidates too big to load
	@#   INCLUDE_UNDERSIZED=1 also show candidates too small (waste the GPU)
	@#   INCLUDE_BASE=1       also show base / non-chat (pretraining) checkpoints
	@#   VRAM_TOLERANCE=<x>   how far above the family max a candidate may go (default 1.25)
	@#   MIN_VRAM_FRAC=<f>    hide models using < this fraction of the GPU (default 0.5)
	@#   NO_HF=1 / NO_OLLAMA=1   skip one source
	@# VRAM budget comes from GPU_MEMORY_GB (exported above; default 24).
	@python3 scripts/catalog-discover.py \
	  $(if $(FAMILY),--family $(FAMILY),) \
	  $(if $(INCLUDE_SAME),--include-same,) \
	  $(if $(INCLUDE_OVERSIZED),--include-oversized,) \
	  $(if $(INCLUDE_UNDERSIZED),--include-undersized,) \
	  $(if $(INCLUDE_BASE),--include-base,) \
	  $(if $(VRAM_TOLERANCE),--vram-tolerance $(VRAM_TOLERANCE),) \
	  $(if $(MIN_VRAM_FRAC),--min-vram-frac $(MIN_VRAM_FRAC),) \
	  $(if $(NO_HF),--no-hf,) \
	  $(if $(NO_OLLAMA),--no-ollama,)

catalog-discover-add: ## Discover, then CONFIRM-add candidates into scripts/model-families.yaml (existing families only). WRITES the file.
	@#   FAMILY=<substr>   scope discovery to matching lineages
	@#   ADD=<repo-id>     add one specific repo non-interactively (skips discovery)
	@#   YES=1             skip the per-add confirmation prompt (scripting)
	@# After adding: make catalog-regen && make probe (probe before relying on it).
	@python3 scripts/catalog-discover.py \
	  $(if $(ADD),--add $(ADD),--add) \
	  $(if $(FAMILY),--family $(FAMILY),) \
	  $(if $(YES),--yes,)

model-status: ## Show the host-local model exclusion ledger (too_big/too_small/unsupported_arch). CLEAR=<name[::backend]> removes an entry.
	@python3 scripts/_model_status.py $(if $(CLEAR),--clear $(CLEAR),)

model-sync: ## Closed loop: diff catalog vs probed+excluded, auto download+probe genuinely-new rows. DRY_RUN=1, SYNC_MAX_DOWNLOADS=<n>, FAMILY=<f>, REGEN=1 (catalog-regen first).
	@$(if $(REGEN),python3 scripts/generate-catalog.py)
	python3 scripts/model-sync.py \
	  $(if $(DRY_RUN),--dry-run,) \
	  $(if $(SYNC_MAX_DOWNLOADS),--max-downloads $(SYNC_MAX_DOWNLOADS),) \
	  $(if $(FAMILY),--family $(FAMILY),)

probe-check: ## Report backend image drift: compare running vLLM/SGLang image digest vs each probe cache's _meta baseline. Exit 1 on drift.
	@CONTAINER_RUNTIME=$(CONTAINER_RUNTIME) \
	  VLLM_IMAGE="$(VLLM_IMAGE)" SGLANG_IMAGE="$(SGLANG_IMAGE)" \
	  python3 scripts/probe-check.py

probe-ornith-arch: ## Tier-1 arch-support probe for the Ornith-1.0 35B (qwen3_5_moe). Cheap: introspects the running vLLM/SGLang images, no weight download.
	@CONTAINER_RUNTIME=$(CONTAINER_RUNTIME) bash scripts/probe-ornith-arch.sh

verify-backend-flags: ## Assert pinned vLLM/SGLang images expose every flag in deploy/backend-flags.yaml (run after image bump)
	python3 scripts/verify-backend-flags.py

# --- NVFP4 quantization (scripts/quant/) ------------------------------------
# Generic + config-driven: set the model + params in .env (see .env.example),
# then `make quant-local` (podman on the local GPU) or `make quant-cloud`
# (HF Jobs). The SAME vars drive both. The ladder is just an .env edit:
#   smoke : QUANT_MODEL=Qwen/Qwen2.5-1.5B-Instruct
#   9B    : QUANT_MODEL=deepreinforce-ai/Ornith-1.0-9B  QUANT_PRESET=ornith QUANT_OUT_NAME=Ornith-1.0-9B-NVFP4
#   35B   : QUANT_MODEL=deepreinforce-ai/Ornith-1.0-35B QUANT_PRESET=ornith QUANT_MOE_ALL_EXPERTS=1
QUANT_SCRIPT          := scripts/quant/quant_smoke.py
QUANT_MODEL           ?= Qwen/Qwen2.5-1.5B-Instruct
QUANT_PRESET          ?= dense
QUANT_SCHEME          ?= NVFP4
QUANT_CALIB_SAMPLES   ?= 128
QUANT_MAX_SEQ         ?= 512
QUANT_DATASET         ?= open_platypus
QUANT_SERVE           ?= transformers
QUANT_MOE_ALL_EXPERTS ?= 0
QUANT_OUT_NAME        ?=
QUANT_PUSH_REPO       ?=
QUANT_IMAGE           ?= docker.io/vllm/vllm-openai:v0.22.1-x86_64-cu129-ubuntu2404
QUANT_FLAVOR          ?= rtx-pro-6000
QUANT_TIMEOUT         ?= 1h
QUANT_HF_CACHE        ?= $(HOME)/.cache/huggingface
QUANT_SAVE_DIR         = $(if $(QUANT_OUT_NAME),$(VLLM_MODELS_DIR)/$(QUANT_OUT_NAME),/root/nvfp4-out)
_QUANT_ARGS = --model $(QUANT_MODEL) --recipe-preset $(QUANT_PRESET) --scheme $(QUANT_SCHEME) --dataset $(QUANT_DATASET) --calib-samples $(QUANT_CALIB_SAMPLES) --max-seq $(QUANT_MAX_SEQ) --serve $(QUANT_SERVE) $(if $(filter 1,$(QUANT_MOE_ALL_EXPERTS)),--moe-all-experts,) $(if $(QUANT_PUSH_REPO),--out $(QUANT_PUSH_REPO),)

.PHONY: quant-local quant-cloud

quant-local: ## NVFP4 quantize on the LOCAL GPU (podman + QUANT_IMAGE); params from .env. Stop the stack first (make cache-down) for VRAM. QUANT_OUT_NAME -> saved under VLLM_MODELS_DIR.
	@echo ">>> local NVFP4: model=$(QUANT_MODEL) preset=$(QUANT_PRESET) scheme=$(QUANT_SCHEME) serve=$(QUANT_SERVE) save=$(QUANT_SAVE_DIR)"
	@mkdir -p $(QUANT_HF_CACHE)
	$(CONTAINER_RUNTIME) run --rm $(GPU_FLAGS) --entrypoint bash \
	    -v $(CURDIR)/scripts/quant:/quant:ro \
	    -v $(VLLM_MODELS_DIR):$(VLLM_MODELS_DIR) \
	    -v $(QUANT_HF_CACHE):/root/.cache/huggingface \
	    -e HF_HUB_ENABLE_HF_TRANSFER=0 -e PYTHONUNBUFFERED=1 \
	    $(if $(QUANT_PUSH_REPO),-e HF_TOKEN=$$HF_TOKEN,) \
	    $(QUANT_IMAGE) -lc 'set -e; pip install --quiet --root-user-action=ignore llmcompressor datasets 2>&1 | tail -1; python3 -u /quant/quant_smoke.py $(_QUANT_ARGS) --save-dir $(QUANT_SAVE_DIR)'

quant-cloud: ## NVFP4 quantize on HF Jobs (QUANT_FLAVOR); params from .env. Needs HF_TOKEN; set QUANT_PUSH_REPO to keep the result.
	@test -n "$$HF_TOKEN" || { echo "ERROR: export HF_TOKEN (huggingface.co/settings/tokens) first"; exit 1; }
	hf jobs uv run --flavor $(QUANT_FLAVOR) --image $(QUANT_IMAGE) --timeout $(QUANT_TIMEOUT) --secrets HF_TOKEN=$$HF_TOKEN $(QUANT_SCRIPT) $(_QUANT_ARGS)

ollama-cleanup-ctx-variants: ## Remove every derived `-ctx<N>` tag from Ollama. Safe — they share weight blobs with parents; only Modelfile metadata is freed.
	@$(CONTAINER_RUNTIME) exec devai-ollama sh -c 'ollama list | awk "NR>1 && \$$1 ~ /-ctx[0-9]+\$$/ {print \$$1}"' | \
	  while IFS= read -r tag; do \
	    [ -n "$$tag" ] || continue; \
	    printf '  rm %s ... ' "$$tag"; \
	    $(CONTAINER_RUNTIME) exec devai-ollama ollama rm "$$tag" >/dev/null 2>&1 \
	      && echo "ok" || echo "FAILED"; \
	  done; \
	  echo; \
	  remaining=$$($(CONTAINER_RUNTIME) exec devai-ollama sh -c 'ollama list | grep -cE -- "-ctx[0-9]+\b"' 2>/dev/null); \
	  echo "  remaining -ctx<N> tags: $$remaining"

vllm-status: ## Show vLLM container status
	@$(CONTAINER_RUNTIME) inspect -f '{{.State.Status}}' devai-vllm 2>/dev/null || echo "not running"
	@$(CONTAINER_RUNTIME) exec devai-vllm curl -sf http://localhost:11434/v1/models 2>/dev/null \
		| python3 -c "import sys,json; [print(f'  {m[\"id\"]}') for m in json.load(sys.stdin)['data']]" 2>/dev/null \
		|| true

vllm-rm: ## Remove a vLLM model (usage: make vllm-rm MODEL=name)
	@if [ -z "$(MODEL)" ]; then echo "Usage: make vllm-rm MODEL=<name>"; exit 1; fi
	@echo "Removing $(MODEL)..."
	rm -rf $(VLLM_MODELS_DIR)/$(MODEL)
	@echo "Done."

vllm-df: ## Show vLLM models disk usage
	@echo "=== vLLM disk usage ==="
	@df -h $(VLLM_MODELS_DIR) 2>/dev/null | tail -1 | awk '{print "  " $$3 " used / " $$2 " total (" $$5 ")"}'
	@echo ""
	@for dir in $(VLLM_MODELS_DIR)/*/; do \
		[ -f "$$dir/config.json" ] || continue; \
		printf "  %-45s %s\n" "$$(basename $$dir)" "$$(du -sh $$dir | cut -f1)"; \
	done


build-router: ## Build the gpu-arbiter router image
	$(CONTAINER_RUNTIME) build --network=host \
		-f deploy/Dockerfile.router \
		-t devai-router .

INSTALL_PREFIX ?= $(HOME)/.local
DEVAI_HOME ?= $(HOME)/.devai

install: ## Install bin/devai-agent to $(INSTALL_PREFIX)/bin and stage config in $(DEVAI_HOME)
	@install -d $(INSTALL_PREFIX)/bin $(DEVAI_HOME) $(DEVAI_HOME)/sessions
	@# Symlink rather than copy — picks up edits to bin/devai-agent without
	@# re-running `make install`. argparse's prog name will show the repo
	@# path in --help; that's honest and a non-issue in practice.
	@ln -sf "$(CURDIR)/bin/devai-agent" $(INSTALL_PREFIX)/bin/devai-agent
	@chmod +x "$(CURDIR)/bin/devai-agent"
	@# Symlink the picker so devai-agent can override the in-image copy via
	@# bind-mount; re-running `make install` after picker edits picks up the
	@# new code without a full image rebuild.
	@ln -sf "$(CURDIR)/scripts/model-picker.py" $(DEVAI_HOME)/model-picker.py
	@# Same for the Capability constants module that the picker imports.
	@# Without this symlink the picker's `from _capability import ...`
	@# would fail when devai-agent bind-mounts the host picker over the
	@# in-image one without bind-mounting the constants module too.
	@ln -sf "$(CURDIR)/scripts/_capability.py" $(DEVAI_HOME)/_capability.py
	@# Symlink each backend's probe cache so it stays fresh as the prober
	@# regenerates it. If users want a frozen snapshot they can replace the
	@# link with a copy after install. Missing caches are warned but not
	@# fatal — the picker tolerates absent backend caches.
	@for cache in ollama vllm sglang; do \
		src="$(CURDIR)/deploy/.$$cache-reasoning-cache.json"; \
		dst="$(DEVAI_HOME)/.$$cache-reasoning-cache.json"; \
		if [ -f "$$src" ]; then \
			ln -sf "$$src" "$$dst"; \
			echo "  linked: $$dst"; \
		else \
			echo "  WARNING: $$src missing — run 'make probe' (or probe-$$cache) first"; \
		fi; \
	done
	@# Bench cache feeds the picker's TPS/CODE/REAS/TOTAL columns. Absent
	@# means those columns render as '-'; not fatal — just unhelpful for
	@# the bench-aware sort modes.
	@bench_src="$(CURDIR)/deploy/.bench-cache.json"; \
	bench_dst="$(DEVAI_HOME)/.bench-cache.json"; \
	if [ -f "$$bench_src" ]; then \
		ln -sf "$$bench_src" "$$bench_dst"; \
		echo "  linked: $$bench_dst"; \
	else \
		echo "  WARNING: $$bench_src missing — run 'make bench-vllm' to populate picker score columns"; \
	fi
	@echo "  linked: $(DEVAI_HOME)/model-picker.py"
	@echo "  installed: $(INSTALL_PREFIX)/bin/devai-agent"
	@echo
	@echo "Next steps:"
	@echo "  1. Add $(INSTALL_PREFIX)/bin to PATH if not already."
	@echo "  2. devai-agent --init     # create $(DEVAI_HOME)/preferences.yaml"
	@echo "  3. devai-agent            # launch the lab + picker"

uninstall: ## Remove devai-agent launcher and the staged config dir
	@rm -f $(INSTALL_PREFIX)/bin/devai-agent
	@rm -f $(DEVAI_HOME)/.ollama-reasoning-cache.json
	@rm -f $(DEVAI_HOME)/.vllm-reasoning-cache.json
	@rm -f $(DEVAI_HOME)/.sglang-reasoning-cache.json
	@rm -f $(DEVAI_HOME)/.bench-cache.json
	@rm -f $(DEVAI_HOME)/model-picker.py
	@rm -f $(DEVAI_HOME)/_capability.py
	@echo "Removed $(INSTALL_PREFIX)/bin/devai-agent and the symlinks under $(DEVAI_HOME)/."
	@echo "preferences.yaml and sessions/ are kept; remove $(DEVAI_HOME)/ manually if you want a clean slate."

install-systemd: ## Install and enable systemd service for infrastructure
	@# Stage every path that deploy/docker-compose.yaml mounts via `./`,
	@# so systemd's WorkingDirectory=$(HOME)/.config/devai resolves to the
	@# same files the repo-side `make cache-up` uses. Mutable JSON caches
	@# and shared scripts are SYMLINKED into the repo so probe/agent writes
	@# in either checkout location stay in sync; static configs are COPIED.
	@mkdir -p $(HOME)/.config/devai $(HOME)/.config/systemd/user
	@# Pre-create the three reasoning-cache JSON files if absent — compose
	@# would otherwise bind-mount a non-existent path and create it as a
	@# DIRECTORY, which then crashes both the router and `make probe` with
	@# `IsADirectoryError`. Idempotent.
	@for f in deploy/.ollama-reasoning-cache.json \
	          deploy/.vllm-reasoning-cache.json \
	          deploy/.sglang-reasoning-cache.json ; do \
	    test -e "$$f" || echo "{}" > "$$f" ; \
	done
	cp deploy/docker-compose.yaml $(HOME)/.config/devai/docker-compose.yaml
	@# Symlink mutable / shared assets from the repo. ln -sfn updates a
	@# pre-existing symlink in place and refuses to clobber a real file
	@# (which the old recipe would leave behind on re-runs).
	ln -sfn $(CURDIR)/deploy/registry-config.yaml          $(HOME)/.config/devai/registry-config.yaml
	ln -sfn $(CURDIR)/deploy/logging.sh                    $(HOME)/.config/devai/logging.sh
	ln -sfn $(CURDIR)/deploy/recovery-flags.json           $(HOME)/.config/devai/recovery-flags.json
	ln -sfn $(CURDIR)/deploy/vllm-plugins.json             $(HOME)/.config/devai/vllm-plugins.json
	@# models.yaml is mounted by the router service (MTP launch params).
	@# Symlinked, not copied, so a `make catalog-regen` in the repo is
	@# picked up without re-running install-systemd; unstaged it would be
	@# bind-mounted as a DIRECTORY and the MTP registry would load empty.
	ln -sfn $(CURDIR)/deploy/models.yaml                   $(HOME)/.config/devai/models.yaml
	ln -sfn $(CURDIR)/deploy/.ollama-reasoning-cache.json  $(HOME)/.config/devai/.ollama-reasoning-cache.json
	ln -sfn $(CURDIR)/deploy/.vllm-reasoning-cache.json    $(HOME)/.config/devai/.vllm-reasoning-cache.json
	ln -sfn $(CURDIR)/deploy/.sglang-reasoning-cache.json  $(HOME)/.config/devai/.sglang-reasoning-cache.json
	ln -sfn $(CURDIR)/deploy/webui-proxy                   $(HOME)/.config/devai/webui-proxy
	cp deploy/systemd/devai-infra.service $(HOME)/.config/systemd/user/
	systemctl --user daemon-reload
	systemctl --user enable --now podman.socket
	systemctl --user enable --now devai-infra.service
	loginctl enable-linger $(USER)
	@echo "Installed to $(HOME)/.config/devai/ and enabled devai-infra.service"

uninstall-systemd: ## Stop, disable and remove the systemd infrastructure unit
	-systemctl --user disable --now devai-infra.service 2>/dev/null
	rm -f $(HOME)/.config/systemd/user/devai-infra.service
	rm -f $(HOME)/.config/devai/docker-compose.yaml
	rm -f $(HOME)/.config/devai/registry-config.yaml
	rm -f $(HOME)/.config/devai/logging.sh
	rm -f $(HOME)/.config/devai/recovery-flags.json
	rm -f $(HOME)/.config/devai/vllm-plugins.json
	rm -f $(HOME)/.config/devai/models.yaml
	rm -f $(HOME)/.config/devai/.ollama-reasoning-cache.json
	rm -f $(HOME)/.config/devai/.vllm-reasoning-cache.json
	rm -f $(HOME)/.config/devai/.sglang-reasoning-cache.json
	rm -f $(HOME)/.config/devai/webui-proxy
	rmdir $(HOME)/.config/devai 2>/dev/null || true
	systemctl --user daemon-reload
	@echo "Removed devai-infra.service and $(HOME)/.config/devai/"


# =============================================================================
# Bench harness — see scripts/bench/ and docs/router.md "Benchmark harness".
# =============================================================================

# Cache mounts mirror what the router uses so the runner reads the same
# probe data the live stack does.
# The two HF weight stores are mounted READ-ONLY so the runner can skip
# models the probe cache advertises but whose weights are not on disk.
# Without them the runner is blind to the store and burns a full task
# sweep per absent model against a router that cannot launch it -- seen
# 2026-07-25, when `make bench-sglang` began benching six models with no
# weights and produced tps=0.0 / ttft=None before it was killed. Same
# `wildcard` guard the lab-image mounts use, so a host without one of the
# volumes still runs.
BENCH_CACHE_MOUNTS = \
	-v $(CURDIR)/scripts:/scripts:ro \
	-v $(CURDIR)/deploy:/deploy \
	-v $(CACHE_DIR)/bench:$(CACHE_DIR)/bench \
	$(if $(wildcard $(VLLM_MODELS_DIR)),-v $(VLLM_MODELS_DIR):$(VLLM_MODELS_DIR):ro) \
	$(if $(wildcard $(SGLANG_MODELS_DIR)),-v $(SGLANG_MODELS_DIR):$(SGLANG_MODELS_DIR):ro)

# n-knobs surface to the runner as both env (for inspect_ai's task
# constructors that read defaults) and CLI flags (the runner reads them
# either way; CLI takes precedence).
BENCH_RUN_FLAGS = \
	$(if $(BENCH_TASKS),--tasks '$(BENCH_TASKS)',) \
	$(if $(BENCH_REPO),--repo '$(BENCH_REPO)',) \
	$(if $(BENCH_CTX),--ctx '$(BENCH_CTX)',) \
	$(if $(BENCH_ALL_CTX),--all-ctx,) \
	$(if $(BENCH_FORCE),--force,) \
	$(if $(BENCH_N_GSM8K),--n-gsm8k $(BENCH_N_GSM8K),) \
	$(if $(BENCH_N_HUMANEVAL),--n-humaneval $(BENCH_N_HUMANEVAL),) \
	$(if $(BENCH_N_TOOLS),--n-tools $(BENCH_N_TOOLS),) \
	$(if $(BENCH_N_MMLU_PRO),--n-mmlu-pro $(BENCH_N_MMLU_PRO),) \
	$(if $(BENCH_N_GPQA),--n-gpqa $(BENCH_N_GPQA),) \
	$(if $(BENCH_DROP_THRESHOLD),--drop-threshold $(BENCH_DROP_THRESHOLD),) \
	$(if $(BENCH_NO_EARLY_DROP),--no-early-drop,) \
	$(if $(BENCH_N_LEAK_PROMPTS),--n-leak-prompts $(BENCH_N_LEAK_PROMPTS),) \
	$(if $(BENCH_N_LONGCTX_FRACTION),--n-longctx-fraction $(BENCH_N_LONGCTX_FRACTION),) \
	$(if $(BENCH_N_LONGCTX_MAX_TOKENS),--n-longctx-max-tokens $(BENCH_N_LONGCTX_MAX_TOKENS),)

bench: bench-vllm bench-sglang bench-ollama ## Bench every probed model on every backend
	@echo
	@echo ">>> bench complete; run 'make bench-report' for the leaderboard"

bench-vllm: ## Bench every loaded vLLM/HF model via devai-router:11435
	@# Pre-condition: devai-router + devai-vllm reachable on devai-net
	@# (run 'make cache-up'). nvidia-smi must be on PATH inside the
	@# lab image so the VRAM sampler reads memory.used.
	@mkdir -p $(CACHE_DIR)/bench/inspect-logs
	$(CONTAINER_RUNTIME) run --rm \
		--network $(DEVAI_NETWORK) \
		$(BENCH_CACHE_MOUNTS) \
		$(GPU_FLAGS) \
		-e GPU_MEMORY_GB=$(GPU_MEMORY_GB) \
		-e HF_TOKEN -e HUGGING_FACE_HUB_TOKEN \
		--entrypoint python3 \
		$(IMAGE_NAME_GPU) \
		/scripts/bench/bench_runner.py --backend vllm \
			$(BENCH_RUN_FLAGS)

bench-sglang: ## Bench every loaded SGLang model via devai-router:11436
	@mkdir -p $(CACHE_DIR)/bench/inspect-logs
	$(CONTAINER_RUNTIME) run --rm \
		--network $(DEVAI_NETWORK) \
		$(BENCH_CACHE_MOUNTS) \
		$(GPU_FLAGS) \
		-e GPU_MEMORY_GB=$(GPU_MEMORY_GB) \
		-e HF_TOKEN -e HUGGING_FACE_HUB_TOKEN \
		--entrypoint python3 \
		$(IMAGE_NAME_GPU) \
		/scripts/bench/bench_runner.py --backend sglang \
			$(BENCH_RUN_FLAGS)

bench-ollama: ## Bench every loaded Ollama model via devai-router:11434
	@mkdir -p $(CACHE_DIR)/bench/inspect-logs
	$(CONTAINER_RUNTIME) run --rm \
		--network $(DEVAI_NETWORK) \
		$(BENCH_CACHE_MOUNTS) \
		$(GPU_FLAGS) \
		-e GPU_MEMORY_GB=$(GPU_MEMORY_GB) \
		-e HF_TOKEN -e HUGGING_FACE_HUB_TOKEN \
		--entrypoint python3 \
		$(IMAGE_NAME_GPU) \
		/scripts/bench/bench_runner.py --backend ollama \
			$(BENCH_RUN_FLAGS)

bench-report: ## Print a Markdown leaderboard from .bench-cache.json
	@$(CONTAINER_RUNTIME) run --rm \
		-v $(CURDIR)/scripts:/scripts:ro \
		-v $(CURDIR)/deploy:/deploy:ro \
		-e GPU_MEMORY_GB=$(GPU_MEMORY_GB) \
		-e HF_TOKEN -e HUGGING_FACE_HUB_TOKEN \
		--entrypoint python3 \
		$(IMAGE_NAME) \
		/scripts/bench/bench_report.py \
			--cache /deploy/.bench-cache.json

test-bench-smoke: ## 1-model tiny-subset smoke test (CI / sanity)
	@# Picks the smallest fitting vLLM model and runs n=5 on every
	@# task type plus n=10 on the latency probe. Should finish in
	@# under 5 minutes on a 24G GPU once the model is warm.
	@mkdir -p $(CACHE_DIR)/bench/inspect-logs
	$(CONTAINER_RUNTIME) run --rm \
		--network $(DEVAI_NETWORK) \
		$(BENCH_CACHE_MOUNTS) \
		$(GPU_FLAGS) \
		-e GPU_MEMORY_GB=$(GPU_MEMORY_GB) \
		-e HF_TOKEN -e HUGGING_FACE_HUB_TOKEN \
		--entrypoint python3 \
		$(IMAGE_NAME_GPU) \
		/scripts/bench/bench_runner.py --backend vllm \
			--repo "Qwen3-8B-NVFP4" \
			--n-gsm8k 5 --n-humaneval 5 --n-tools 4 --n-leak-prompts 10 \
			--force
