package main

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Argv golden corpus.
//
// sglang-backend-remediation Phase 3 changes three things that touch the
// launch command line -- `--tp` -> `--tp-size`, `%.2f` -> `%.4f` on the
// memory fraction, and a new `--served-model-name` -- and each was
// argued to be a no-op or a strict improvement. This corpus converts that
// argument into a checked diff: every entrypoint is rendered across a
// matrix of launch configs and compared byte-for-byte against a frozen
// file.
//
// It is deliberately NOT a set of hand-written expectations. Those encode
// what the author believed; a golden file encodes what the code did, so a
// change nobody intended shows up as a diff in review rather than as a
// silent behaviour shift on the next cold start.
//
// Regenerate INTENTIONALLY after reviewing the diff:
//
//	go test ./gpu-arbiter -run TestArgvGoldenCorpus -update
//
// Generalises the technique already used by
// `make test-probe-ollama-idempotent`.

var updateGolden = flag.Bool("update", false, "rewrite the argv golden corpus")

// goldenCase is one row of the matrix. Names are stable and sorted in the
// output so a diff is readable.
type goldenCase struct {
	Name  string
	Model string
	LC    launchConfig
}

func goldenCases() []goldenCase {
	tp := func(b bool) *bool { return &b }
	return []goldenCase{
		{
			Name:  "minimal",
			Model: "Qwen3-8B-NVFP4",
			LC:    launchConfig{MemFraction: 0.9, MaxContext: 32768},
		},
		{
			Name:  "typical-nvfp4-128k",
			Model: "gpt-oss-20b",
			LC: launchConfig{
				MemFraction: 0.8836, MaxContext: 131072, MaxNumSeqs: 32,
				ReasoningParser: "gpt-oss", ToolParser: "gpt-oss",
			},
		},
		{
			Name:  "max-context-256k",
			Model: "Gemma-4-26B-A4B-it-NVFP4",
			LC: launchConfig{
				MemFraction: 0.92, MaxContext: 262144, MaxNumSeqs: 32,
				ToolParser: "gemma4",
			},
		},
		{
			Name:  "kv-fp8",
			Model: "Qwen3.5-9B-NVFP4",
			LC: launchConfig{
				MemFraction: 0.9, MaxContext: 131072, MaxNumSeqs: 32,
				KVCacheType: "fp8", ReasoningParser: "qwen3",
			},
		},
		{
			Name:  "kv-auto-emits-nothing",
			Model: "Qwen3.5-9B-NVFP4",
			LC: launchConfig{
				MemFraction: 0.9, MaxContext: 65536, KVCacheType: "auto",
			},
		},
		{
			Name:  "ollama-q8-kv",
			Model: "qwen3.6:35b-a3b-mtp-q4_K_M",
			LC: launchConfig{
				MemFraction: 0.9, MaxContext: 131072,
				KVCacheType: "q8_0", FlashAttention: tp(true),
			},
		},
		{
			Name:  "max-num-seqs-zero-omits-flag",
			Model: "Qwen3-14B-NVFP4",
			LC:    launchConfig{MemFraction: 0.9, MaxContext: 32768, MaxNumSeqs: 0},
		},
		{
			Name:  "recovery-flags-last",
			Model: "Qwen3.6-27B-NVFP4",
			LC: launchConfig{
				MemFraction: 0.9, MaxContext: 32768, MaxNumSeqs: 32,
				ReasoningParser: "qwen3",
				RecoveryFlags:   []string{"--enforce-eager"},
			},
		},
		{
			Name:  "plugin-paths-vllm-only",
			Model: "NVIDIA-Nemotron-Nano-9B-v2-NVFP4",
			LC: launchConfig{
				MemFraction: 0.9, MaxContext: 131072, MaxNumSeqs: 32,
				ReasoningParser: "nemotron_3", ToolParser: "nemotron_json",
				ReasoningParserPlugin: "/plugins/nemotron_reasoning.py",
				ToolParserPlugin:      "/plugins/nemotron_tool.py",
			},
		},
	}
}

func renderGoldenCorpus() string {
	var b strings.Builder
	b.WriteString("# argv golden corpus -- generated by TestArgvGoldenCorpus -update\n")
	b.WriteString("# One block per (backend, case). Review diffs; do not edit by hand.\n")
	for _, backend := range []string{"ollama", "vllm", "sglang"} {
		entry := map[string]func(string, launchConfig) []string{
			"ollama": ollamaEntrypoint,
			"vllm":   vllmEntrypoint,
			"sglang": sglangEntrypoint,
		}[backend]
		for _, tc := range goldenCases() {
			b.WriteString("\n== " + backend + " / " + tc.Name + "\n")
			argv := entry(tc.Model, tc.LC)
			enc, err := json.MarshalIndent(argv, "", "  ")
			if err != nil {
				b.WriteString("ERROR: " + err.Error() + "\n")
				continue
			}
			b.Write(enc)
			b.WriteString("\n")
		}
	}
	return b.String()
}

func TestArgvGoldenCorpus(t *testing.T) {
	path := filepath.Join("testdata", "argv-golden.txt")
	got := renderGoldenCorpus()

	if *updateGolden {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("golden corpus rewritten: %s", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden (run with -update to create): %v", err)
	}
	if got != string(want) {
		t.Errorf("argv changed against the frozen corpus.\n"+
			"If the change is INTENDED, review the diff and re-run:\n"+
			"  go test ./gpu-arbiter -run TestArgvGoldenCorpus -update\n\n%s",
			firstDiff(string(want), got))
	}
}

// firstDiff reports the first differing line with a little context, which
// is far more useful in CI output than dumping two multi-KB blobs.
func firstDiff(want, got string) string {
	w := strings.Split(want, "\n")
	g := strings.Split(got, "\n")
	for i := 0; i < len(w) || i < len(g); i++ {
		var wl, gl string
		if i < len(w) {
			wl = w[i]
		}
		if i < len(g) {
			gl = g[i]
		}
		if wl != gl {
			ctx := ""
			if i > 0 && i-1 < len(w) {
				ctx = "  context: " + w[i-1] + "\n"
			}
			return ctx +
				"  line " + itoa(i+1) + "\n" +
				"    want: " + wl + "\n" +
				"    got:  " + gl + "\n"
		}
	}
	return "  (no line differs; trailing-newline mismatch)"
}
